//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

import "errors"

type AlliancePkgAllianceMeta struct {
	Id          int32
	UpgradeCost int32
	MemberNum   int32
	AdminNum    int32
	LevelIcon   string
}

const TypeId_AlliancePkgAllianceMeta = 1628002901

func (*AlliancePkgAllianceMeta) GetTypeId() int32 {
	return 1628002901
}

func NewAlliancePkgAllianceMeta(_buf map[string]interface{}) (_v *AlliancePkgAllianceMeta, err error) {
	_v = &AlliancePkgAllianceMeta{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_upgrade_cost__ interface{}
		if __json_upgrade_cost__, _ok_ = _buf["upgrade_cost"]; !_ok_ || __json_upgrade_cost__ == nil {
			err = errors.New("upgrade_cost error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_upgrade_cost__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.UpgradeCost = __x__
		}
	}
	{
		var _ok_ bool
		var __json_member_num__ interface{}
		if __json_member_num__, _ok_ = _buf["member_num"]; !_ok_ || __json_member_num__ == nil {
			err = errors.New("member_num error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_member_num__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.MemberNum = __x__
		}
	}
	{
		var _ok_ bool
		var __json_admin_num__ interface{}
		if __json_admin_num__, _ok_ = _buf["admin_num"]; !_ok_ || __json_admin_num__ == nil {
			err = errors.New("admin_num error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_admin_num__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.AdminNum = __x__
		}
	}
	{
		var _ok_ bool
		var __json_level_icon__ interface{}
		if __json_level_icon__, _ok_ = _buf["level_icon"]; !_ok_ || __json_level_icon__ == nil {
			err = errors.New("level_icon error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_level_icon__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.LevelIcon = __x__
		}
	}
	return
}
