//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type AlliancePkgExpTable struct {
	_dataMap  map[int32]*AlliancePkgExpMeta
	_dataList []*AlliancePkgExpMeta
}

func NewAlliancePkgExpTable(_buf []map[string]interface{}) (*AlliancePkgExpTable, error) {
	_dataList := make([]*AlliancePkgExpMeta, 0, len(_buf))
	dataMap := make(map[int32]*AlliancePkgExpMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewAlliancePkgExpMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &AlliancePkgExpTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *AlliancePkgExpTable) GetDataMap() map[int32]*AlliancePkgExpMeta {
	return table._dataMap
}

func (table *AlliancePkgExpTable) GetDataList() []*AlliancePkgExpMeta {
	return table._dataList
}

func (table *AlliancePkgExpTable) Get(key int32) *AlliancePkgExpMeta {
	return table._dataMap[key]
}
