//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

import "errors"

type CollectEnergy struct {
	CollectCount int32
	Rate         int32
}

const TypeId_CollectEnergy = -1054103502

func (*CollectEnergy) GetTypeId() int32 {
	return -1054103502
}

func NewCollectEnergy(_buf map[string]interface{}) (_v *CollectEnergy, err error) {
	_v = &CollectEnergy{}
	{
		var _ok_ bool
		var __json_collect_count__ interface{}
		if __json_collect_count__, _ok_ = _buf["collect_count"]; !_ok_ || __json_collect_count__ == nil {
			err = errors.New("collect_count error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_collect_count__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.CollectCount = __x__
		}
	}
	{
		var _ok_ bool
		var __json_rate__ interface{}
		if __json_rate__, _ok_ = _buf["rate"]; !_ok_ || __json_rate__ == nil {
			err = errors.New("rate error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_rate__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Rate = __x__
		}
	}
	return
}
