//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type DutyPkgSigninTable struct {
	_dataMap  map[int32]*DutyPkgSigninMeta
	_dataList []*DutyPkgSigninMeta
}

func NewDutyPkgSigninTable(_buf []map[string]interface{}) (*DutyPkgSigninTable, error) {
	_dataList := make([]*DutyPkgSigninMeta, 0, len(_buf))
	dataMap := make(map[int32]*DutyPkgSigninMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewDutyPkgSigninMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &DutyPkgSigninTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *DutyPkgSigninTable) GetDataMap() map[int32]*DutyPkgSigninMeta {
	return table._dataMap
}

func (table *DutyPkgSigninTable) GetDataList() []*DutyPkgSigninMeta {
	return table._dataList
}

func (table *DutyPkgSigninTable) Get(key int32) *DutyPkgSigninMeta {
	return table._dataMap[key]
}
