//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type DutyPkgActiveMeta struct {
	Id            int32
	DailyRewards  []*KeyVal
	WeeklyRewards []*KeyVal
}

const TypeId_DutyPkgActiveMeta = -747135933

func (*DutyPkgActiveMeta) GetTypeId() int32 {
	return -747135933
}

func NewDutyPkgActiveMeta(_buf map[string]interface{}) (_v *DutyPkgActiveMeta, err error) {
	_v = &DutyPkgActiveMeta{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_daily_rewards__ interface{}
		if __json_daily_rewards__, _ok_ = _buf["daily_rewards"]; !_ok_ || __json_daily_rewards__ == nil {
			err = errors.New("daily_rewards error")
			return
		} else {
			var __x__ []*KeyVal
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_daily_rewards__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]*KeyVal, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ *KeyVal
					{
						var _ok_ bool
						var _x_ map[string]interface{}
						if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
						if _list_v0_, err = NewKeyVal(_x_); err != nil {
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.DailyRewards = __x__
		}
	}
	{
		var _ok_ bool
		var __json_weekly_rewards__ interface{}
		if __json_weekly_rewards__, _ok_ = _buf["weekly_rewards"]; !_ok_ || __json_weekly_rewards__ == nil {
			err = errors.New("weekly_rewards error")
			return
		} else {
			var __x__ []*KeyVal
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_weekly_rewards__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]*KeyVal, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ *KeyVal
					{
						var _ok_ bool
						var _x_ map[string]interface{}
						if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
						if _list_v0_, err = NewKeyVal(_x_); err != nil {
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.WeeklyRewards = __x__
		}
	}
	return
}
