//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type DutyPkgCalendarsTable struct {
	_dataMap  map[int32]*DutyPkgCalendarsMeta
	_dataList []*DutyPkgCalendarsMeta
}

func NewDutyPkgCalendarsTable(_buf []map[string]interface{}) (*DutyPkgCalendarsTable, error) {
	_dataList := make([]*DutyPkgCalendarsMeta, 0, len(_buf))
	dataMap := make(map[int32]*DutyPkgCalendarsMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewDutyPkgCalendarsMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &DutyPkgCalendarsTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *DutyPkgCalendarsTable) GetDataMap() map[int32]*DutyPkgCalendarsMeta {
	return table._dataMap
}

func (table *DutyPkgCalendarsTable) GetDataList() []*DutyPkgCalendarsMeta {
	return table._dataList
}

func (table *DutyPkgCalendarsTable) Get(key int32) *DutyPkgCalendarsMeta {
	return table._dataMap[key]
}
