//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type DutyPkgDutyTaskTable struct {
	_dataMap  map[int32]*DutyPkgDutyTaskMeta
	_dataList []*DutyPkgDutyTaskMeta
}

func NewDutyPkgDutyTaskTable(_buf []map[string]interface{}) (*DutyPkgDutyTaskTable, error) {
	_dataList := make([]*DutyPkgDutyTaskMeta, 0, len(_buf))
	dataMap := make(map[int32]*DutyPkgDutyTaskMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewDutyPkgDutyTaskMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &DutyPkgDutyTaskTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *DutyPkgDutyTaskTable) GetDataMap() map[int32]*DutyPkgDutyTaskMeta {
	return table._dataMap
}

func (table *DutyPkgDutyTaskTable) GetDataList() []*DutyPkgDutyTaskMeta {
	return table._dataList
}

func (table *DutyPkgDutyTaskTable) Get(key int32) *DutyPkgDutyTaskMeta {
	return table._dataMap[key]
}
