//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type EquipPkgEquipTable struct {
	_dataMap  map[int32]*EquipPkgEquipMeta
	_dataList []*EquipPkgEquipMeta
}

func NewEquipPkgEquipTable(_buf []map[string]interface{}) (*EquipPkgEquipTable, error) {
	_dataList := make([]*EquipPkgEquipMeta, 0, len(_buf))
	dataMap := make(map[int32]*EquipPkgEquipMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewEquipPkgEquipMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &EquipPkgEquipTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *EquipPkgEquipTable) GetDataMap() map[int32]*EquipPkgEquipMeta {
	return table._dataMap
}

func (table *EquipPkgEquipTable) GetDataList() []*EquipPkgEquipMeta {
	return table._dataList
}

func (table *EquipPkgEquipTable) Get(key int32) *EquipPkgEquipMeta {
	return table._dataMap[key]
}
