//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type EquipPkgPoolTable struct {
	_dataMap  map[int32]*EquipPkgPoolMeta
	_dataList []*EquipPkgPoolMeta
}

func NewEquipPkgPoolTable(_buf []map[string]interface{}) (*EquipPkgPoolTable, error) {
	_dataList := make([]*EquipPkgPoolMeta, 0, len(_buf))
	dataMap := make(map[int32]*EquipPkgPoolMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewEquipPkgPoolMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &EquipPkgPoolTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *EquipPkgPoolTable) GetDataMap() map[int32]*EquipPkgPoolMeta {
	return table._dataMap
}

func (table *EquipPkgPoolTable) GetDataList() []*EquipPkgPoolMeta {
	return table._dataList
}

func (table *EquipPkgPoolTable) Get(key int32) *EquipPkgPoolMeta {
	return table._dataMap[key]
}
