//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type EquipPkgAtrLinkTable struct {
	_dataMap  map[int32]*EquipPkgAtrLinkMeta
	_dataList []*EquipPkgAtrLinkMeta
}

func NewEquipPkgAtrLinkTable(_buf []map[string]interface{}) (*EquipPkgAtrLinkTable, error) {
	_dataList := make([]*EquipPkgAtrLinkMeta, 0, len(_buf))
	dataMap := make(map[int32]*EquipPkgAtrLinkMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewEquipPkgAtrLinkMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &EquipPkgAtrLinkTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *EquipPkgAtrLinkTable) GetDataMap() map[int32]*EquipPkgAtrLinkMeta {
	return table._dataMap
}

func (table *EquipPkgAtrLinkTable) GetDataList() []*EquipPkgAtrLinkMeta {
	return table._dataList
}

func (table *EquipPkgAtrLinkTable) Get(key int32) *EquipPkgAtrLinkMeta {
	return table._dataMap[key]
}
