//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

import "errors"

type FuncPkgFuncMeta struct {
	Id          int32
	SystemName  string
	Unlocklevel int32
	UnlockType  int32
	UnlockParam int32
}

const TypeId_FuncPkgFuncMeta = -265467409

func (*FuncPkgFuncMeta) GetTypeId() int32 {
	return -265467409
}

func NewFuncPkgFuncMeta(_buf map[string]interface{}) (_v *FuncPkgFuncMeta, err error) {
	_v = &FuncPkgFuncMeta{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_system_name__ interface{}
		if __json_system_name__, _ok_ = _buf["system_name"]; !_ok_ || __json_system_name__ == nil {
			err = errors.New("system_name error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_system_name__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.SystemName = __x__
		}
	}
	{
		var _ok_ bool
		var __json_unlocklevel__ interface{}
		if __json_unlocklevel__, _ok_ = _buf["unlocklevel"]; !_ok_ || __json_unlocklevel__ == nil {
			err = errors.New("unlocklevel error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_unlocklevel__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Unlocklevel = __x__
		}
	}
	{
		var _ok_ bool
		var __json_unlock_type__ interface{}
		if __json_unlock_type__, _ok_ = _buf["unlock_type"]; !_ok_ || __json_unlock_type__ == nil {
			err = errors.New("unlock_type error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_unlock_type__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.UnlockType = __x__
		}
	}
	{
		var _ok_ bool
		var __json_unlock_param__ interface{}
		if __json_unlock_param__, _ok_ = _buf["unlock_param"]; !_ok_ || __json_unlock_param__ == nil {
			err = errors.New("unlock_param error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_unlock_param__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.UnlockParam = __x__
		}
	}
	return
}
