//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type GameShopPkgRecommendTable struct {
	_dataMap  map[int32]*GameShopPkgRecommendMeta
	_dataList []*GameShopPkgRecommendMeta
}

func NewGameShopPkgRecommendTable(_buf []map[string]interface{}) (*GameShopPkgRecommendTable, error) {
	_dataList := make([]*GameShopPkgRecommendMeta, 0, len(_buf))
	dataMap := make(map[int32]*GameShopPkgRecommendMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewGameShopPkgRecommendMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &GameShopPkgRecommendTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *GameShopPkgRecommendTable) GetDataMap() map[int32]*GameShopPkgRecommendMeta {
	return table._dataMap
}

func (table *GameShopPkgRecommendTable) GetDataList() []*GameShopPkgRecommendMeta {
	return table._dataList
}

func (table *GameShopPkgRecommendTable) Get(key int32) *GameShopPkgRecommendMeta {
	return table._dataMap[key]
}
