//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type GameShopPkgMonthCardTable struct {
	_dataMap  map[int32]*GameShopPkgMonthCardMeta
	_dataList []*GameShopPkgMonthCardMeta
}

func NewGameShopPkgMonthCardTable(_buf []map[string]interface{}) (*GameShopPkgMonthCardTable, error) {
	_dataList := make([]*GameShopPkgMonthCardMeta, 0, len(_buf))
	dataMap := make(map[int32]*GameShopPkgMonthCardMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewGameShopPkgMonthCardMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &GameShopPkgMonthCardTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *GameShopPkgMonthCardTable) GetDataMap() map[int32]*GameShopPkgMonthCardMeta {
	return table._dataMap
}

func (table *GameShopPkgMonthCardTable) GetDataList() []*GameShopPkgMonthCardMeta {
	return table._dataList
}

func (table *GameShopPkgMonthCardTable) Get(key int32) *GameShopPkgMonthCardMeta {
	return table._dataMap[key]
}
