//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

import "errors"

type ItemPkgGroupMeta struct {
	Id          int32
	ItemGroupId int32
	ItemId      int32
	ItemNum     int32
	ItemWeight  int32
}

const TypeId_ItemPkgGroupMeta = -2114237713

func (*ItemPkgGroupMeta) GetTypeId() int32 {
	return -2114237713
}

func NewItemPkgGroupMeta(_buf map[string]interface{}) (_v *ItemPkgGroupMeta, err error) {
	_v = &ItemPkgGroupMeta{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_item_group_id__ interface{}
		if __json_item_group_id__, _ok_ = _buf["item_group_id"]; !_ok_ || __json_item_group_id__ == nil {
			err = errors.New("item_group_id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_item_group_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.ItemGroupId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_item_id__ interface{}
		if __json_item_id__, _ok_ = _buf["item_id"]; !_ok_ || __json_item_id__ == nil {
			err = errors.New("item_id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_item_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.ItemId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_item_num__ interface{}
		if __json_item_num__, _ok_ = _buf["item_num"]; !_ok_ || __json_item_num__ == nil {
			err = errors.New("item_num error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_item_num__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.ItemNum = __x__
		}
	}
	{
		var _ok_ bool
		var __json_item_weight__ interface{}
		if __json_item_weight__, _ok_ = _buf["item_weight"]; !_ok_ || __json_item_weight__ == nil {
			err = errors.New("item_weight error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_item_weight__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.ItemWeight = __x__
		}
	}
	return
}
