//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type ItemReward struct {
	ItemId int32
	Num    int32
}

const TypeId_ItemReward = -343558078

func (*ItemReward) GetTypeId() int32 {
	return -343558078
}

func NewItemReward(_buf map[string]interface{}) (_v *ItemReward, err error) {
	_v = &ItemReward{}
	{
		var _ok_ bool
		var __json_item_id__ interface{}
		if __json_item_id__, _ok_ = _buf["item_id"]; !_ok_ || __json_item_id__ == nil {
			err = errors.New("item_id error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_item_id__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.ItemId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_num__ interface{}
		if __json_num__, _ok_ = _buf["num"]; !_ok_ || __json_num__ == nil {
			err = errors.New("num error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_num__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Num = __x__
		}
	}
	return
}
