//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type ItemPkgItemDropTable struct {
	_dataMap  map[int32]*ItemPkgDropMeta
	_dataList []*ItemPkgDropMeta
}

func NewItemPkgItemDropTable(_buf []map[string]interface{}) (*ItemPkgItemDropTable, error) {
	_dataList := make([]*ItemPkgDropMeta, 0, len(_buf))
	dataMap := make(map[int32]*ItemPkgDropMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewItemPkgDropMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &ItemPkgItemDropTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *ItemPkgItemDropTable) GetDataMap() map[int32]*ItemPkgDropMeta {
	return table._dataMap
}

func (table *ItemPkgItemDropTable) GetDataList() []*ItemPkgDropMeta {
	return table._dataList
}

func (table *ItemPkgItemDropTable) Get(key int32) *ItemPkgDropMeta {
	return table._dataMap[key]
}
