//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package meta

type TaskPkgTaskGroupTable struct {
	_dataMap  map[int32]*TaskPkgTaskGroupMeta
	_dataList []*TaskPkgTaskGroupMeta
}

func NewTaskPkgTaskGroupTable(_buf []map[string]interface{}) (*TaskPkgTaskGroupTable, error) {
	_dataList := make([]*TaskPkgTaskGroupMeta, 0, len(_buf))
	dataMap := make(map[int32]*TaskPkgTaskGroupMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewTaskPkgTaskGroupMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TaskPkgTaskGroupTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TaskPkgTaskGroupTable) GetDataMap() map[int32]*TaskPkgTaskGroupMeta {
	return table._dataMap
}

func (table *TaskPkgTaskGroupTable) GetDataList() []*TaskPkgTaskGroupMeta {
	return table._dataList
}

func (table *TaskPkgTaskGroupTable) Get(key int32) *TaskPkgTaskGroupMeta {
	return table._dataMap[key]
}
