//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TaskPkgTaskTable struct {
	_dataMap  map[int32]*TaskPkgTaskMeta
	_dataList []*TaskPkgTaskMeta
}

func NewTaskPkgTaskTable(_buf []map[string]interface{}) (*TaskPkgTaskTable, error) {
	_dataList := make([]*TaskPkgTaskMeta, 0, len(_buf))
	dataMap := make(map[int32]*TaskPkgTaskMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewTaskPkgTaskMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TaskPkgTaskTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TaskPkgTaskTable) GetDataMap() map[int32]*TaskPkgTaskMeta {
	return table._dataMap
}

func (table *TaskPkgTaskTable) GetDataList() []*TaskPkgTaskMeta {
	return table._dataList
}

func (table *TaskPkgTaskTable) Get(key int32) *TaskPkgTaskMeta {
	return table._dataMap[key]
}
