//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TaskPkgTriggerTable struct {
	_dataMap  map[int32]*TaskPkgTriggerMeta
	_dataList []*TaskPkgTriggerMeta
}

func NewTaskPkgTriggerTable(_buf []map[string]interface{}) (*TaskPkgTriggerTable, error) {
	_dataList := make([]*TaskPkgTriggerMeta, 0, len(_buf))
	dataMap := make(map[int32]*TaskPkgTriggerMeta)

	for _, _ele_ := range _buf {
		if _v, err2 := NewTaskPkgTriggerMeta(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TaskPkgTriggerTable{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TaskPkgTriggerTable) GetDataMap() map[int32]*TaskPkgTriggerMeta {
	return table._dataMap
}

func (table *TaskPkgTriggerTable) GetDataList() []*TaskPkgTriggerMeta {
	return table._dataList
}

func (table *TaskPkgTriggerTable) Get(key int32) *TaskPkgTriggerMeta {
	return table._dataMap[key]
}
