// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// activity excel - 活动类型
type ActivityExcelType int32

const (
	ActivityExcelType_AE_TYPE_MIN    ActivityExcelType = 0
	ActivityExcelType_AE_TYPE_task   ActivityExcelType = 1 // 任务
	ActivityExcelType_AE_TYPE_signin ActivityExcelType = 2 // 签到
	ActivityExcelType_AE_TYPE_MAX    ActivityExcelType = 3
)

// Enum value maps for ActivityExcelType.
var (
	ActivityExcelType_name = map[int32]string{
		0: "AE_TYPE_MIN",
		1: "AE_TYPE_task",
		2: "AE_TYPE_signin",
		3: "AE_TYPE_MAX",
	}
	ActivityExcelType_value = map[string]int32{
		"AE_TYPE_MIN":    0,
		"AE_TYPE_task":   1,
		"AE_TYPE_signin": 2,
		"AE_TYPE_MAX":    3,
	}
)

func (x ActivityExcelType) Enum() *ActivityExcelType {
	p := new(ActivityExcelType)
	*p = x
	return p
}

func (x ActivityExcelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityExcelType) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_proto_enumTypes[0].Descriptor()
}

func (ActivityExcelType) Type() protoreflect.EnumType {
	return &file_activity_proto_enumTypes[0]
}

func (x ActivityExcelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityExcelType.Descriptor instead.
func (ActivityExcelType) EnumDescriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

// activity excel - 活动时间类型
type ActivityExcelTimeType int32

const (
	ActivityExcelTimeType_AE_TIME_TYPE_MIN        ActivityExcelTimeType = 0
	ActivityExcelTimeType_AE_TIME_TYPE_newbie     ActivityExcelTimeType = 101 // 新手活动(跟随游戏数据)
	ActivityExcelTimeType_AE_TIME_TYPE_background ActivityExcelTimeType = 102 // 后台配置
	ActivityExcelTimeType_AE_TIME_TYPE_MAX        ActivityExcelTimeType = 3
)

// Enum value maps for ActivityExcelTimeType.
var (
	ActivityExcelTimeType_name = map[int32]string{
		0:   "AE_TIME_TYPE_MIN",
		101: "AE_TIME_TYPE_newbie",
		102: "AE_TIME_TYPE_background",
		3:   "AE_TIME_TYPE_MAX",
	}
	ActivityExcelTimeType_value = map[string]int32{
		"AE_TIME_TYPE_MIN":        0,
		"AE_TIME_TYPE_newbie":     101,
		"AE_TIME_TYPE_background": 102,
		"AE_TIME_TYPE_MAX":        3,
	}
)

func (x ActivityExcelTimeType) Enum() *ActivityExcelTimeType {
	p := new(ActivityExcelTimeType)
	*p = x
	return p
}

func (x ActivityExcelTimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityExcelTimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_proto_enumTypes[1].Descriptor()
}

func (ActivityExcelTimeType) Type() protoreflect.EnumType {
	return &file_activity_proto_enumTypes[1]
}

func (x ActivityExcelTimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityExcelTimeType.Descriptor instead.
func (ActivityExcelTimeType) EnumDescriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{1}
}

type C2LS_ActivityListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2LS_ActivityListReq) Reset() {
	*x = C2LS_ActivityListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ActivityListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ActivityListReq) ProtoMessage() {}

func (x *C2LS_ActivityListReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ActivityListReq.ProtoReflect.Descriptor instead.
func (*C2LS_ActivityListReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

type LS2C_ActivityListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"` // 修改客户端数据缓存
}

func (x *LS2C_ActivityListRes) Reset() {
	*x = LS2C_ActivityListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ActivityListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ActivityListRes) ProtoMessage() {}

func (x *LS2C_ActivityListRes) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ActivityListRes.ProtoReflect.Descriptor instead.
func (*LS2C_ActivityListRes) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_ActivityListRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_FetchActivityRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int32 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	DayIndex   int32 `protobuf:"varint,2,opt,name=day_index,json=dayIndex,proto3" json:"day_index,omitempty"`
	ElementId  int32 `protobuf:"varint,3,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"` // (七日任务:taskId)
}

func (x *C2LS_FetchActivityRewardReq) Reset() {
	*x = C2LS_FetchActivityRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_FetchActivityRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_FetchActivityRewardReq) ProtoMessage() {}

func (x *C2LS_FetchActivityRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_FetchActivityRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_FetchActivityRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{2}
}

func (x *C2LS_FetchActivityRewardReq) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *C2LS_FetchActivityRewardReq) GetDayIndex() int32 {
	if x != nil {
		return x.DayIndex
	}
	return 0
}

func (x *C2LS_FetchActivityRewardReq) GetElementId() int32 {
	if x != nil {
		return x.ElementId
	}
	return 0
}

type LS2C_FetchActivityRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DropChange *DropChange `protobuf:"bytes,1,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"` // 修改客户端数据缓存
}

func (x *LS2C_FetchActivityRewardRes) Reset() {
	*x = LS2C_FetchActivityRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_FetchActivityRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_FetchActivityRewardRes) ProtoMessage() {}

func (x *LS2C_FetchActivityRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_FetchActivityRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_FetchActivityRewardRes) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{3}
}

func (x *LS2C_FetchActivityRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

func (x *LS2C_FetchActivityRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_OneKeyActivityRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int32 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
}

func (x *C2LS_OneKeyActivityRewardReq) Reset() {
	*x = C2LS_OneKeyActivityRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_OneKeyActivityRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_OneKeyActivityRewardReq) ProtoMessage() {}

func (x *C2LS_OneKeyActivityRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_OneKeyActivityRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_OneKeyActivityRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{4}
}

func (x *C2LS_OneKeyActivityRewardReq) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type LS2C_OneKeyActivityRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DropChange *DropChange `protobuf:"bytes,1,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"` // 修改客户端数据缓存
}

func (x *LS2C_OneKeyActivityRewardRes) Reset() {
	*x = LS2C_OneKeyActivityRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_OneKeyActivityRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_OneKeyActivityRewardRes) ProtoMessage() {}

func (x *LS2C_OneKeyActivityRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_OneKeyActivityRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_OneKeyActivityRewardRes) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{5}
}

func (x *LS2C_OneKeyActivityRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

func (x *LS2C_OneKeyActivityRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

var File_activity_proto protoreflect.FileDescriptor

var file_activity_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x32,
	0x4c, 0x53, 0x5f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x22, 0x47, 0x0a, 0x14, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7a, 0x0a, 0x1b, 0x43,
	0x32, 0x4c, 0x53, 0x5f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x61, 0x79, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x64, 0x61, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x1b, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x1c, 0x43, 0x32, 0x4c, 0x53, 0x5f,
	0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x1c, 0x4c, 0x53, 0x32, 0x43,
	0x5f, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72,
	0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x5c, 0x0a, 0x12, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x41, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x74, 0x61, 0x73, 0x6b,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x73, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0x03, 0x2a, 0x7a, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x45, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x6e, 0x65, 0x77, 0x62, 0x69, 0x65, 0x10, 0x65,
	0x12, 0x1b, 0x0a, 0x17, 0x41, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x66, 0x12, 0x14, 0x0a,
	0x10, 0x41, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41,
	0x58, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_activity_proto_rawDescOnce sync.Once
	file_activity_proto_rawDescData = file_activity_proto_rawDesc
)

func file_activity_proto_rawDescGZIP() []byte {
	file_activity_proto_rawDescOnce.Do(func() {
		file_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_activity_proto_rawDescData)
	})
	return file_activity_proto_rawDescData
}

var file_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_activity_proto_goTypes = []interface{}{
	(ActivityExcelType)(0),               // 0: pb.ActivityExcel_type
	(ActivityExcelTimeType)(0),           // 1: pb.ActivityExcel_timeType
	(*C2LS_ActivityListReq)(nil),         // 2: pb.C2LS_ActivityListReq
	(*LS2C_ActivityListRes)(nil),         // 3: pb.LS2C_ActivityListRes
	(*C2LS_FetchActivityRewardReq)(nil),  // 4: pb.C2LS_FetchActivityRewardReq
	(*LS2C_FetchActivityRewardRes)(nil),  // 5: pb.LS2C_FetchActivityRewardRes
	(*C2LS_OneKeyActivityRewardReq)(nil), // 6: pb.C2LS_OneKeyActivityRewardReq
	(*LS2C_OneKeyActivityRewardRes)(nil), // 7: pb.LS2C_OneKeyActivityRewardRes
	(*CliComData)(nil),                   // 8: pb.CliComData
	(*DropChange)(nil),                   // 9: pb.DropChange
}
var file_activity_proto_depIdxs = []int32{
	8, // 0: pb.LS2C_ActivityListRes.common_data:type_name -> pb.CliComData
	9, // 1: pb.LS2C_FetchActivityRewardRes.dropChange:type_name -> pb.DropChange
	8, // 2: pb.LS2C_FetchActivityRewardRes.common_data:type_name -> pb.CliComData
	9, // 3: pb.LS2C_OneKeyActivityRewardRes.dropChange:type_name -> pb.DropChange
	8, // 4: pb.LS2C_OneKeyActivityRewardRes.common_data:type_name -> pb.CliComData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_activity_proto_init() }
func file_activity_proto_init() {
	if File_activity_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ActivityListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ActivityListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_FetchActivityRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_FetchActivityRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_OneKeyActivityRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_OneKeyActivityRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activity_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_proto_goTypes,
		DependencyIndexes: file_activity_proto_depIdxs,
		EnumInfos:         file_activity_proto_enumTypes,
		MessageInfos:      file_activity_proto_msgTypes,
	}.Build()
	File_activity_proto = out.File
	file_activity_proto_rawDesc = nil
	file_activity_proto_goTypes = nil
	file_activity_proto_depIdxs = nil
}
