// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.1
// source: base.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BaseRpc_RpcCall_FullMethodName = "/pb.BaseRpc/RpcCall"
)

// BaseRpcClient is the client API for BaseRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseRpcClient interface {
	RpcCall(ctx context.Context, in *RpcCallReq, opts ...grpc.CallOption) (*RpcCallRet, error)
}

type baseRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseRpcClient(cc grpc.ClientConnInterface) BaseRpcClient {
	return &baseRpcClient{cc}
}

func (c *baseRpcClient) RpcCall(ctx context.Context, in *RpcCallReq, opts ...grpc.CallOption) (*RpcCallRet, error) {
	out := new(RpcCallRet)
	err := c.cc.Invoke(ctx, BaseRpc_RpcCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseRpcServer is the server API for BaseRpc service.
// All implementations must embed UnimplementedBaseRpcServer
// for forward compatibility
type BaseRpcServer interface {
	RpcCall(context.Context, *RpcCallReq) (*RpcCallRet, error)
	mustEmbedUnimplementedBaseRpcServer()
}

// UnimplementedBaseRpcServer must be embedded to have forward compatible implementations.
type UnimplementedBaseRpcServer struct {
}

func (UnimplementedBaseRpcServer) RpcCall(context.Context, *RpcCallReq) (*RpcCallRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcCall not implemented")
}
func (UnimplementedBaseRpcServer) mustEmbedUnimplementedBaseRpcServer() {}

// UnsafeBaseRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseRpcServer will
// result in compilation errors.
type UnsafeBaseRpcServer interface {
	mustEmbedUnimplementedBaseRpcServer()
}

func RegisterBaseRpcServer(s grpc.ServiceRegistrar, srv BaseRpcServer) {
	s.RegisterService(&BaseRpc_ServiceDesc, srv)
}

func _BaseRpc_RpcCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseRpcServer).RpcCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseRpc_RpcCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseRpcServer).RpcCall(ctx, req.(*RpcCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseRpc_ServiceDesc is the grpc.ServiceDesc for BaseRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BaseRpc",
	HandlerType: (*BaseRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcCall",
			Handler:    _BaseRpc_RpcCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base.proto",
}
