// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: card.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2LS_CardLevelUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId int32           `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Items  []*KeyValueItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *C2LS_CardLevelUpReq) Reset() {
	*x = C2LS_CardLevelUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardLevelUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardLevelUpReq) ProtoMessage() {}

func (x *C2LS_CardLevelUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardLevelUpReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardLevelUpReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *C2LS_CardLevelUpReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardLevelUpReq) GetItems() []*KeyValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LS2C_CardLevelUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardLevelUpRes) Reset() {
	*x = LS2C_CardLevelUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardLevelUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardLevelUpRes) ProtoMessage() {}

func (x *LS2C_CardLevelUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardLevelUpRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardLevelUpRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_CardLevelUpRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_CardBreakthroughReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_CardBreakthroughReq) Reset() {
	*x = C2LS_CardBreakthroughReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardBreakthroughReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardBreakthroughReq) ProtoMessage() {}

func (x *C2LS_CardBreakthroughReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardBreakthroughReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardBreakthroughReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *C2LS_CardBreakthroughReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type LS2C_CardBreakthroughRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	DropChange *DropChange `protobuf:"bytes,2,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
}

func (x *LS2C_CardBreakthroughRes) Reset() {
	*x = LS2C_CardBreakthroughRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardBreakthroughRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardBreakthroughRes) ProtoMessage() {}

func (x *LS2C_CardBreakthroughRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardBreakthroughRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardBreakthroughRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{3}
}

func (x *LS2C_CardBreakthroughRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_CardBreakthroughRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

type C2LS_CardSkillUpgradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Index  uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *C2LS_CardSkillUpgradeReq) Reset() {
	*x = C2LS_CardSkillUpgradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardSkillUpgradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardSkillUpgradeReq) ProtoMessage() {}

func (x *C2LS_CardSkillUpgradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardSkillUpgradeReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardSkillUpgradeReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{4}
}

func (x *C2LS_CardSkillUpgradeReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardSkillUpgradeReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type LS2C_CardSkillUpgradeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardSkillUpgradeRes) Reset() {
	*x = LS2C_CardSkillUpgradeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardSkillUpgradeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardSkillUpgradeRes) ProtoMessage() {}

func (x *LS2C_CardSkillUpgradeRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardSkillUpgradeRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardSkillUpgradeRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{5}
}

func (x *LS2C_CardSkillUpgradeRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_CardRecoveryHPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId []uint32 `protobuf:"varint,1,rep,packed,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_CardRecoveryHPReq) Reset() {
	*x = C2LS_CardRecoveryHPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardRecoveryHPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardRecoveryHPReq) ProtoMessage() {}

func (x *C2LS_CardRecoveryHPReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardRecoveryHPReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardRecoveryHPReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{6}
}

func (x *C2LS_CardRecoveryHPReq) GetCardId() []uint32 {
	if x != nil {
		return x.CardId
	}
	return nil
}

type LS2C_CardRecoveryHPRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardRecoveryHPRes) Reset() {
	*x = LS2C_CardRecoveryHPRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardRecoveryHPRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardRecoveryHPRes) ProtoMessage() {}

func (x *LS2C_CardRecoveryHPRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardRecoveryHPRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardRecoveryHPRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{7}
}

func (x *LS2C_CardRecoveryHPRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_CardUpgradeStarLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_CardUpgradeStarLevelReq) Reset() {
	*x = C2LS_CardUpgradeStarLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardUpgradeStarLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardUpgradeStarLevelReq) ProtoMessage() {}

func (x *C2LS_CardUpgradeStarLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardUpgradeStarLevelReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardUpgradeStarLevelReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{8}
}

func (x *C2LS_CardUpgradeStarLevelReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type LS2C_CardUpgradeStarLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardUpgradeStarLevelRes) Reset() {
	*x = LS2C_CardUpgradeStarLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardUpgradeStarLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardUpgradeStarLevelRes) ProtoMessage() {}

func (x *LS2C_CardUpgradeStarLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardUpgradeStarLevelRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardUpgradeStarLevelRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{9}
}

func (x *LS2C_CardUpgradeStarLevelRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_CardCompoundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_CardCompoundReq) Reset() {
	*x = C2LS_CardCompoundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardCompoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardCompoundReq) ProtoMessage() {}

func (x *C2LS_CardCompoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardCompoundReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardCompoundReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{10}
}

func (x *C2LS_CardCompoundReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type LS2C_CardCompoundRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardCompoundRes) Reset() {
	*x = LS2C_CardCompoundRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardCompoundRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardCompoundRes) ProtoMessage() {}

func (x *LS2C_CardCompoundRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardCompoundRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardCompoundRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{11}
}

func (x *LS2C_CardCompoundRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 性格升级
type C2LS_CardCharacterBreakReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_CardCharacterBreakReq) Reset() {
	*x = C2LS_CardCharacterBreakReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardCharacterBreakReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardCharacterBreakReq) ProtoMessage() {}

func (x *C2LS_CardCharacterBreakReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardCharacterBreakReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardCharacterBreakReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{12}
}

func (x *C2LS_CardCharacterBreakReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type LS2C_CardCharacterBreakRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardCharacterBreakRes) Reset() {
	*x = LS2C_CardCharacterBreakRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardCharacterBreakRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardCharacterBreakRes) ProtoMessage() {}

func (x *LS2C_CardCharacterBreakRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardCharacterBreakRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardCharacterBreakRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{13}
}

func (x *LS2C_CardCharacterBreakRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 性格解锁
type C2LS_CardCharacterUnlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId      int32         `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CharacterId CharacterType `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3,enum=pb.CharacterType" json:"character_id,omitempty"` // 详见 CharacterType
}

func (x *C2LS_CardCharacterUnlockReq) Reset() {
	*x = C2LS_CardCharacterUnlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardCharacterUnlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardCharacterUnlockReq) ProtoMessage() {}

func (x *C2LS_CardCharacterUnlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardCharacterUnlockReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardCharacterUnlockReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{14}
}

func (x *C2LS_CardCharacterUnlockReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardCharacterUnlockReq) GetCharacterId() CharacterType {
	if x != nil {
		return x.CharacterId
	}
	return CharacterType_CharacterType_None
}

type LS2C_CardCharacterUnlockRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardCharacterUnlockRes) Reset() {
	*x = LS2C_CardCharacterUnlockRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardCharacterUnlockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardCharacterUnlockRes) ProtoMessage() {}

func (x *LS2C_CardCharacterUnlockRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardCharacterUnlockRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardCharacterUnlockRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{15}
}

func (x *LS2C_CardCharacterUnlockRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 性格切换
type C2LS_CardCharacterChangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId      int32         `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CharacterId CharacterType `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3,enum=pb.CharacterType" json:"character_id,omitempty"`
}

func (x *C2LS_CardCharacterChangeReq) Reset() {
	*x = C2LS_CardCharacterChangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardCharacterChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardCharacterChangeReq) ProtoMessage() {}

func (x *C2LS_CardCharacterChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardCharacterChangeReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardCharacterChangeReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{16}
}

func (x *C2LS_CardCharacterChangeReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardCharacterChangeReq) GetCharacterId() CharacterType {
	if x != nil {
		return x.CharacterId
	}
	return CharacterType_CharacterType_None
}

type LS2C_CardCharacterChangeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardCharacterChangeRes) Reset() {
	*x = LS2C_CardCharacterChangeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardCharacterChangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardCharacterChangeRes) ProtoMessage() {}

func (x *LS2C_CardCharacterChangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardCharacterChangeRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardCharacterChangeRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{17}
}

func (x *LS2C_CardCharacterChangeRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 好感度剧情首通奖励
type C2LS_CardFavoriteStoryRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId  int32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Section int32 `protobuf:"varint,2,opt,name=section,proto3" json:"section,omitempty"` // 阶段对应的好感度等级
}

func (x *C2LS_CardFavoriteStoryRewardReq) Reset() {
	*x = C2LS_CardFavoriteStoryRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardFavoriteStoryRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardFavoriteStoryRewardReq) ProtoMessage() {}

func (x *C2LS_CardFavoriteStoryRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardFavoriteStoryRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardFavoriteStoryRewardReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{18}
}

func (x *C2LS_CardFavoriteStoryRewardReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardFavoriteStoryRewardReq) GetSection() int32 {
	if x != nil {
		return x.Section
	}
	return 0
}

type LS2C_CardFavoriteStoryRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CardFavoriteStoryRewardRes) Reset() {
	*x = LS2C_CardFavoriteStoryRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardFavoriteStoryRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardFavoriteStoryRewardRes) ProtoMessage() {}

func (x *LS2C_CardFavoriteStoryRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardFavoriteStoryRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardFavoriteStoryRewardRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{19}
}

func (x *LS2C_CardFavoriteStoryRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 使用好感度道具
type C2LS_CardFavoriteItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32          `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Items  []*KeyValueItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *C2LS_CardFavoriteItemReq) Reset() {
	*x = C2LS_CardFavoriteItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CardFavoriteItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CardFavoriteItemReq) ProtoMessage() {}

func (x *C2LS_CardFavoriteItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CardFavoriteItemReq.ProtoReflect.Descriptor instead.
func (*C2LS_CardFavoriteItemReq) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{20}
}

func (x *C2LS_CardFavoriteItemReq) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *C2LS_CardFavoriteItemReq) GetItems() []*KeyValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LS2C_CardFavoriteItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData     `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	Items      []*KeyValueItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *LS2C_CardFavoriteItemRes) Reset() {
	*x = LS2C_CardFavoriteItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CardFavoriteItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CardFavoriteItemRes) ProtoMessage() {}

func (x *LS2C_CardFavoriteItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CardFavoriteItemRes.ProtoReflect.Descriptor instead.
func (*LS2C_CardFavoriteItemRes) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{21}
}

func (x *LS2C_CardFavoriteItemRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_CardFavoriteItemRes) GetItems() []*KeyValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_card_proto protoreflect.FileDescriptor

var file_card_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x13, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43,
	0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x46,
	0x0a, 0x13, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x18, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43,
	0x61, 0x72, 0x64, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x7b, 0x0a, 0x18, 0x4c,
	0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x74, 0x68, 0x72,
	0x6f, 0x75, 0x67, 0x68, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72,
	0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x49, 0x0a, 0x18, 0x43, 0x32, 0x4c, 0x53,
	0x5f, 0x43, 0x61, 0x72, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x4b, 0x0a, 0x18, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x31, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x48, 0x50, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x48, 0x50, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x37,
	0x0a, 0x1c, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x1c, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x43, 0x61, 0x72, 0x64, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x14, 0x43, 0x32, 0x4c, 0x53,
	0x5f, 0x43, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x14, 0x4c, 0x53, 0x32,
	0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x35, 0x0a, 0x1a, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x1a, 0x4c, 0x53, 0x32,
	0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x42,
	0x72, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x1b, 0x43, 0x32, 0x4c, 0x53,
	0x5f, 0x43, 0x61, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x12, 0x34, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x1b, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43,
	0x61, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x1b, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43,
	0x61, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x1b, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72,
	0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x1f, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x61, 0x72,
	0x64, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x1f, 0x4c, 0x53,
	0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b,
	0x0a, 0x18, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x73, 0x0a, 0x18, 0x4c,
	0x53, 0x32, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData = file_card_proto_rawDesc
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_card_proto_rawDescData)
	})
	return file_card_proto_rawDescData
}

var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_card_proto_goTypes = []interface{}{
	(*C2LS_CardLevelUpReq)(nil),             // 0: pb.C2LS_CardLevelUpReq
	(*LS2C_CardLevelUpRes)(nil),             // 1: pb.LS2C_CardLevelUpRes
	(*C2LS_CardBreakthroughReq)(nil),        // 2: pb.C2LS_CardBreakthroughReq
	(*LS2C_CardBreakthroughRes)(nil),        // 3: pb.LS2C_CardBreakthroughRes
	(*C2LS_CardSkillUpgradeReq)(nil),        // 4: pb.C2LS_CardSkillUpgradeReq
	(*LS2C_CardSkillUpgradeRes)(nil),        // 5: pb.LS2C_CardSkillUpgradeRes
	(*C2LS_CardRecoveryHPReq)(nil),          // 6: pb.C2LS_CardRecoveryHPReq
	(*LS2C_CardRecoveryHPRes)(nil),          // 7: pb.LS2C_CardRecoveryHPRes
	(*C2LS_CardUpgradeStarLevelReq)(nil),    // 8: pb.C2LS_CardUpgradeStarLevelReq
	(*LS2C_CardUpgradeStarLevelRes)(nil),    // 9: pb.LS2C_CardUpgradeStarLevelRes
	(*C2LS_CardCompoundReq)(nil),            // 10: pb.C2LS_CardCompoundReq
	(*LS2C_CardCompoundRes)(nil),            // 11: pb.LS2C_CardCompoundRes
	(*C2LS_CardCharacterBreakReq)(nil),      // 12: pb.C2LS_CardCharacterBreakReq
	(*LS2C_CardCharacterBreakRes)(nil),      // 13: pb.LS2C_CardCharacterBreakRes
	(*C2LS_CardCharacterUnlockReq)(nil),     // 14: pb.C2LS_CardCharacterUnlockReq
	(*LS2C_CardCharacterUnlockRes)(nil),     // 15: pb.LS2C_CardCharacterUnlockRes
	(*C2LS_CardCharacterChangeReq)(nil),     // 16: pb.C2LS_CardCharacterChangeReq
	(*LS2C_CardCharacterChangeRes)(nil),     // 17: pb.LS2C_CardCharacterChangeRes
	(*C2LS_CardFavoriteStoryRewardReq)(nil), // 18: pb.C2LS_CardFavoriteStoryRewardReq
	(*LS2C_CardFavoriteStoryRewardRes)(nil), // 19: pb.LS2C_CardFavoriteStoryRewardRes
	(*C2LS_CardFavoriteItemReq)(nil),        // 20: pb.C2LS_CardFavoriteItemReq
	(*LS2C_CardFavoriteItemRes)(nil),        // 21: pb.LS2C_CardFavoriteItemRes
	(*KeyValueItem)(nil),                    // 22: pb.KeyValueItem
	(*CliComData)(nil),                      // 23: pb.CliComData
	(*DropChange)(nil),                      // 24: pb.DropChange
	(CharacterType)(0),                      // 25: pb.CharacterType
}
var file_card_proto_depIdxs = []int32{
	22, // 0: pb.C2LS_CardLevelUpReq.items:type_name -> pb.KeyValueItem
	23, // 1: pb.LS2C_CardLevelUpRes.common_data:type_name -> pb.CliComData
	23, // 2: pb.LS2C_CardBreakthroughRes.common_data:type_name -> pb.CliComData
	24, // 3: pb.LS2C_CardBreakthroughRes.dropChange:type_name -> pb.DropChange
	23, // 4: pb.LS2C_CardSkillUpgradeRes.common_data:type_name -> pb.CliComData
	23, // 5: pb.LS2C_CardRecoveryHPRes.common_data:type_name -> pb.CliComData
	23, // 6: pb.LS2C_CardUpgradeStarLevelRes.common_data:type_name -> pb.CliComData
	23, // 7: pb.LS2C_CardCompoundRes.common_data:type_name -> pb.CliComData
	23, // 8: pb.LS2C_CardCharacterBreakRes.common_data:type_name -> pb.CliComData
	25, // 9: pb.C2LS_CardCharacterUnlockReq.character_id:type_name -> pb.CharacterType
	23, // 10: pb.LS2C_CardCharacterUnlockRes.common_data:type_name -> pb.CliComData
	25, // 11: pb.C2LS_CardCharacterChangeReq.character_id:type_name -> pb.CharacterType
	23, // 12: pb.LS2C_CardCharacterChangeRes.common_data:type_name -> pb.CliComData
	23, // 13: pb.LS2C_CardFavoriteStoryRewardRes.common_data:type_name -> pb.CliComData
	22, // 14: pb.C2LS_CardFavoriteItemReq.items:type_name -> pb.KeyValueItem
	23, // 15: pb.LS2C_CardFavoriteItemRes.common_data:type_name -> pb.CliComData
	22, // 16: pb.LS2C_CardFavoriteItemRes.items:type_name -> pb.KeyValueItem
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardLevelUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardLevelUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardBreakthroughReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardBreakthroughRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardSkillUpgradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardSkillUpgradeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardRecoveryHPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardRecoveryHPRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardUpgradeStarLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardUpgradeStarLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardCompoundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardCompoundRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardCharacterBreakReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardCharacterBreakRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardCharacterUnlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardCharacterUnlockRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardCharacterChangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardCharacterChangeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardFavoriteStoryRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardFavoriteStoryRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CardFavoriteItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CardFavoriteItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_rawDesc = nil
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
