// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatChannel int32

const (
	ChatChannel_Channel_None     ChatChannel = 0 // 占位符
	ChatChannel_Channel_system   ChatChannel = 1 // 系统
	ChatChannel_Channel_recruit  ChatChannel = 2 // 招募
	ChatChannel_Channel_alliance ChatChannel = 3 // 联盟
	ChatChannel_Channel_private  ChatChannel = 4 // 私人
	ChatChannel_Channel_invited  ChatChannel = 5 // 好友邀请
	ChatChannel_Channel_Max      ChatChannel = 7 // 占位符
)

// Enum value maps for ChatChannel.
var (
	ChatChannel_name = map[int32]string{
		0: "Channel_None",
		1: "Channel_system",
		2: "Channel_recruit",
		3: "Channel_alliance",
		4: "Channel_private",
		5: "Channel_invited",
		7: "Channel_Max",
	}
	ChatChannel_value = map[string]int32{
		"Channel_None":     0,
		"Channel_system":   1,
		"Channel_recruit":  2,
		"Channel_alliance": 3,
		"Channel_private":  4,
		"Channel_invited":  5,
		"Channel_Max":      7,
	}
)

func (x ChatChannel) Enum() *ChatChannel {
	p := new(ChatChannel)
	*p = x
	return p
}

func (x ChatChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (ChatChannel) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x ChatChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatChannel.Descriptor instead.
func (ChatChannel) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

// //////////////////////////////////////////////////////////// 内部actor调用
// 加入房间请求
type S2S_JoinChatRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 房间id
}

func (x *S2S_JoinChatRoomReq) Reset() {
	*x = S2S_JoinChatRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_JoinChatRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_JoinChatRoomReq) ProtoMessage() {}

func (x *S2S_JoinChatRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_JoinChatRoomReq.ProtoReflect.Descriptor instead.
func (*S2S_JoinChatRoomReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *S2S_JoinChatRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type S2S_JoinChatRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_JoinChatRoomRes) Reset() {
	*x = S2S_JoinChatRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_JoinChatRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_JoinChatRoomRes) ProtoMessage() {}

func (x *S2S_JoinChatRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_JoinChatRoomRes.ProtoReflect.Descriptor instead.
func (*S2S_JoinChatRoomRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

// 获取对应频道聊天消息
type S2S_GetChannelMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"` // 房间id
}

func (x *S2S_GetChannelMessageReq) Reset() {
	*x = S2S_GetChannelMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_GetChannelMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_GetChannelMessageReq) ProtoMessage() {}

func (x *S2S_GetChannelMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_GetChannelMessageReq.ProtoReflect.Descriptor instead.
func (*S2S_GetChannelMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *S2S_GetChannelMessageReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type S2S_GetChannelMessageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []*BroadMessage `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"` // 消息
}

func (x *S2S_GetChannelMessageRes) Reset() {
	*x = S2S_GetChannelMessageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_GetChannelMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_GetChannelMessageRes) ProtoMessage() {}

func (x *S2S_GetChannelMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_GetChannelMessageRes.ProtoReflect.Descriptor instead.
func (*S2S_GetChannelMessageRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *S2S_GetChannelMessageRes) GetMessage() []*BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 房间邀请好友
type S2S_InvitedFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromRoleId uint64        `protobuf:"varint,1,opt,name=from_roleId,json=fromRoleId,proto3" json:"from_roleId,omitempty"` //发送邀请roleId
	Message    *BroadMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ToObject   uint64        `protobuf:"varint,3,opt,name=ToObject,proto3" json:"ToObject,omitempty"` // 好友RoleId
}

func (x *S2S_InvitedFriendReq) Reset() {
	*x = S2S_InvitedFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_InvitedFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_InvitedFriendReq) ProtoMessage() {}

func (x *S2S_InvitedFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_InvitedFriendReq.ProtoReflect.Descriptor instead.
func (*S2S_InvitedFriendReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *S2S_InvitedFriendReq) GetFromRoleId() uint64 {
	if x != nil {
		return x.FromRoleId
	}
	return 0
}

func (x *S2S_InvitedFriendReq) GetMessage() *BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *S2S_InvitedFriendReq) GetToObject() uint64 {
	if x != nil {
		return x.ToObject
	}
	return 0
}

type S2S_InvitedFriendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_InvitedFriendRes) Reset() {
	*x = S2S_InvitedFriendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_InvitedFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_InvitedFriendRes) ProtoMessage() {}

func (x *S2S_InvitedFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_InvitedFriendRes.ProtoReflect.Descriptor instead.
func (*S2S_InvitedFriendRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

// 私聊向好友推送消息
type S2S_PushMessageToUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromRoleId uint64        `protobuf:"varint,1,opt,name=from_roleId,json=fromRoleId,proto3" json:"from_roleId,omitempty"` //发送消息者roleId
	Message    *BroadMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 消息
	ToRoleId   uint64        `protobuf:"varint,3,opt,name=to_roleId,json=toRoleId,proto3" json:"to_roleId,omitempty"`       // 接受消息roleId
	ChannelId  ChatChannel   `protobuf:"varint,4,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
}

func (x *S2S_PushMessageToUserReq) Reset() {
	*x = S2S_PushMessageToUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_PushMessageToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_PushMessageToUserReq) ProtoMessage() {}

func (x *S2S_PushMessageToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_PushMessageToUserReq.ProtoReflect.Descriptor instead.
func (*S2S_PushMessageToUserReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *S2S_PushMessageToUserReq) GetFromRoleId() uint64 {
	if x != nil {
		return x.FromRoleId
	}
	return 0
}

func (x *S2S_PushMessageToUserReq) GetMessage() *BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *S2S_PushMessageToUserReq) GetToRoleId() uint64 {
	if x != nil {
		return x.ToRoleId
	}
	return 0
}

func (x *S2S_PushMessageToUserReq) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

type S2S_PushMessageToUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_PushMessageToUserRes) Reset() {
	*x = S2S_PushMessageToUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_PushMessageToUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_PushMessageToUserRes) ProtoMessage() {}

func (x *S2S_PushMessageToUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_PushMessageToUserRes.ProtoReflect.Descriptor instead.
func (*S2S_PushMessageToUserRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

// 获取聊天消息 client --> userActor
type C2LS_GetChatMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId ChatChannel `protobuf:"varint,1,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
	Target    uint64      `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`                           // 好友RoleId,或者联盟ID
	FromSize  int32       `protobuf:"varint,3,opt,name=fromSize,proto3" json:"fromSize,omitempty"`                       // 消息开始索引
	Size      int32       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                               //消息结束索引
}

func (x *C2LS_GetChatMessageReq) Reset() {
	*x = C2LS_GetChatMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_GetChatMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_GetChatMessageReq) ProtoMessage() {}

func (x *C2LS_GetChatMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_GetChatMessageReq.ProtoReflect.Descriptor instead.
func (*C2LS_GetChatMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *C2LS_GetChatMessageReq) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

func (x *C2LS_GetChatMessageReq) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *C2LS_GetChatMessageReq) GetFromSize() int32 {
	if x != nil {
		return x.FromSize
	}
	return 0
}

func (x *C2LS_GetChatMessageReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LS2C_GetChatMessageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId ChatChannel     `protobuf:"varint,1,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
	Message   []*BroadMessage `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`                          // 消息
}

func (x *LS2C_GetChatMessageRes) Reset() {
	*x = LS2C_GetChatMessageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_GetChatMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_GetChatMessageRes) ProtoMessage() {}

func (x *LS2C_GetChatMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_GetChatMessageRes.ProtoReflect.Descriptor instead.
func (*LS2C_GetChatMessageRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *LS2C_GetChatMessageRes) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

func (x *LS2C_GetChatMessageRes) GetMessage() []*BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 发送消息
type C2LS_SendChatMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId ChatChannel `protobuf:"varint,1,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
	Message   string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 消息
	ToObject  uint64      `protobuf:"varint,3,opt,name=toObject,proto3" json:"toObject,omitempty"`                       // 发送目标, 玩家RoleId 或 联盟Id
}

func (x *C2LS_SendChatMessageReq) Reset() {
	*x = C2LS_SendChatMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_SendChatMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_SendChatMessageReq) ProtoMessage() {}

func (x *C2LS_SendChatMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_SendChatMessageReq.ProtoReflect.Descriptor instead.
func (*C2LS_SendChatMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *C2LS_SendChatMessageReq) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

func (x *C2LS_SendChatMessageReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *C2LS_SendChatMessageReq) GetToObject() uint64 {
	if x != nil {
		return x.ToObject
	}
	return 0
}

type LS2C_SendChatMessageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *BroadMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` //
}

func (x *LS2C_SendChatMessageRes) Reset() {
	*x = LS2C_SendChatMessageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_SendChatMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_SendChatMessageRes) ProtoMessage() {}

func (x *LS2C_SendChatMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_SendChatMessageRes.ProtoReflect.Descriptor instead.
func (*LS2C_SendChatMessageRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *LS2C_SendChatMessageRes) GetMessage() *BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// 标记消息已读
type C2LS_HasReadMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendRoleId uint64 `protobuf:"varint,1,opt,name=friend_roleId,json=friendRoleId,proto3" json:"friend_roleId,omitempty"`
}

func (x *C2LS_HasReadMessageReq) Reset() {
	*x = C2LS_HasReadMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_HasReadMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_HasReadMessageReq) ProtoMessage() {}

func (x *C2LS_HasReadMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_HasReadMessageReq.ProtoReflect.Descriptor instead.
func (*C2LS_HasReadMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *C2LS_HasReadMessageReq) GetFriendRoleId() uint64 {
	if x != nil {
		return x.FriendRoleId
	}
	return 0
}

type LS2C_HasReadMessageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_HasReadMessageRes) Reset() {
	*x = LS2C_HasReadMessageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_HasReadMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_HasReadMessageRes) ProtoMessage() {}

func (x *LS2C_HasReadMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_HasReadMessageRes.ProtoReflect.Descriptor instead.
func (*LS2C_HasReadMessageRes) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *LS2C_HasReadMessageRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 广播消息 chatActor --> client
type LS2C_NotifyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId  ChatChannel          `protobuf:"varint,1,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
	Message    []*BroadMessage      `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`                          // 消息
	ExtraValue int32                `protobuf:"varint,3,opt,name=extraValue,proto3" json:"extraValue,omitempty"`                   //  系统消息时候，等于联盟Id,要在联盟里显示
	RoleInfo   *PCommonRoleBaseInfo `protobuf:"bytes,4,opt,name=roleInfo,proto3" json:"roleInfo,omitempty"`                        // 发送消息的roleInfo
}

func (x *LS2C_NotifyMessage) Reset() {
	*x = LS2C_NotifyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_NotifyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_NotifyMessage) ProtoMessage() {}

func (x *LS2C_NotifyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_NotifyMessage.ProtoReflect.Descriptor instead.
func (*LS2C_NotifyMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *LS2C_NotifyMessage) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

func (x *LS2C_NotifyMessage) GetMessage() []*BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LS2C_NotifyMessage) GetExtraValue() int32 {
	if x != nil {
		return x.ExtraValue
	}
	return 0
}

func (x *LS2C_NotifyMessage) GetRoleInfo() *PCommonRoleBaseInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

// 推送好友消息
type LS2C_NotifyPrivateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId ChatChannel          `protobuf:"varint,1,opt,name=channelId,proto3,enum=pb.ChatChannel" json:"channelId,omitempty"` // 频道Id
	Message   *BroadMessage        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 消息
	RoleInfo  *PCommonRoleBaseInfo `protobuf:"bytes,3,opt,name=roleInfo,proto3" json:"roleInfo,omitempty"`                        // 发送消息的roleInfo
}

func (x *LS2C_NotifyPrivateMessage) Reset() {
	*x = LS2C_NotifyPrivateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_NotifyPrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_NotifyPrivateMessage) ProtoMessage() {}

func (x *LS2C_NotifyPrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_NotifyPrivateMessage.ProtoReflect.Descriptor instead.
func (*LS2C_NotifyPrivateMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *LS2C_NotifyPrivateMessage) GetChannelId() ChatChannel {
	if x != nil {
		return x.ChannelId
	}
	return ChatChannel_Channel_None
}

func (x *LS2C_NotifyPrivateMessage) GetMessage() *BroadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LS2C_NotifyPrivateMessage) GetRoleInfo() *PCommonRoleBaseInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

type AllianceMemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`  // 名称
	RoleHead int32  `protobuf:"varint,2,opt,name=role_head,json=roleHead,proto3" json:"role_head,omitempty"` // 头像id
}

func (x *AllianceMemInfo) Reset() {
	*x = AllianceMemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceMemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceMemInfo) ProtoMessage() {}

func (x *AllianceMemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceMemInfo.ProtoReflect.Descriptor instead.
func (*AllianceMemInfo) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{16}
}

func (x *AllianceMemInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AllianceMemInfo) GetRoleHead() int32 {
	if x != nil {
		return x.RoleHead
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

var file_chat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x32, 0x53, 0x5f, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x32, 0x53, 0x5f, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x18,
	0x53, 0x32, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x22, 0x46, 0x0a, 0x18, 0x53, 0x32, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7f, 0x0a, 0x14, 0x53, 0x32, 0x53, 0x5f,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x54, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x54, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x32, 0x53,
	0x5f, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x22, 0xb3, 0x01, 0x0a, 0x18, 0x53, 0x32, 0x53, 0x5f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x6f, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x74, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x32, 0x53, 0x5f, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2d,
	0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x73, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x2d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7e, 0x0a, 0x17, 0x43, 0x32,
	0x4c, 0x53, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x74, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x45, 0x0a, 0x17, 0x4c, 0x53,
	0x32, 0x43, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3d, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x48, 0x61, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x48, 0x61, 0x73, 0x52, 0x65, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0xc4, 0x01, 0x0a, 0x12,
	0x4c, 0x53, 0x32, 0x43, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x33, 0x0a,
	0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x19, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x4b, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x2a, 0x99, 0x01,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x72,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x03, 0x12, 0x13,
	0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x07, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData = file_chat_proto_rawDesc
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_proto_rawDescData)
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_chat_proto_goTypes = []interface{}{
	(ChatChannel)(0),                  // 0: pb.ChatChannel
	(*S2S_JoinChatRoomReq)(nil),       // 1: pb.S2S_JoinChatRoomReq
	(*S2S_JoinChatRoomRes)(nil),       // 2: pb.S2S_JoinChatRoomRes
	(*S2S_GetChannelMessageReq)(nil),  // 3: pb.S2S_GetChannelMessageReq
	(*S2S_GetChannelMessageRes)(nil),  // 4: pb.S2S_GetChannelMessageRes
	(*S2S_InvitedFriendReq)(nil),      // 5: pb.S2S_InvitedFriendReq
	(*S2S_InvitedFriendRes)(nil),      // 6: pb.S2S_InvitedFriendRes
	(*S2S_PushMessageToUserReq)(nil),  // 7: pb.S2S_PushMessageToUserReq
	(*S2S_PushMessageToUserRes)(nil),  // 8: pb.S2S_PushMessageToUserRes
	(*C2LS_GetChatMessageReq)(nil),    // 9: pb.C2LS_GetChatMessageReq
	(*LS2C_GetChatMessageRes)(nil),    // 10: pb.LS2C_GetChatMessageRes
	(*C2LS_SendChatMessageReq)(nil),   // 11: pb.C2LS_SendChatMessageReq
	(*LS2C_SendChatMessageRes)(nil),   // 12: pb.LS2C_SendChatMessageRes
	(*C2LS_HasReadMessageReq)(nil),    // 13: pb.C2LS_HasReadMessageReq
	(*LS2C_HasReadMessageRes)(nil),    // 14: pb.LS2C_HasReadMessageRes
	(*LS2C_NotifyMessage)(nil),        // 15: pb.LS2C_NotifyMessage
	(*LS2C_NotifyPrivateMessage)(nil), // 16: pb.LS2C_NotifyPrivateMessage
	(*AllianceMemInfo)(nil),           // 17: pb.AllianceMemInfo
	(*BroadMessage)(nil),              // 18: pb.BroadMessage
	(*CliComData)(nil),                // 19: pb.CliComData
	(*PCommonRoleBaseInfo)(nil),       // 20: pb.PCommonRoleBaseInfo
}
var file_chat_proto_depIdxs = []int32{
	18, // 0: pb.S2S_GetChannelMessageRes.message:type_name -> pb.BroadMessage
	18, // 1: pb.S2S_InvitedFriendReq.message:type_name -> pb.BroadMessage
	18, // 2: pb.S2S_PushMessageToUserReq.message:type_name -> pb.BroadMessage
	0,  // 3: pb.S2S_PushMessageToUserReq.channelId:type_name -> pb.ChatChannel
	0,  // 4: pb.C2LS_GetChatMessageReq.channelId:type_name -> pb.ChatChannel
	0,  // 5: pb.LS2C_GetChatMessageRes.channelId:type_name -> pb.ChatChannel
	18, // 6: pb.LS2C_GetChatMessageRes.message:type_name -> pb.BroadMessage
	0,  // 7: pb.C2LS_SendChatMessageReq.channelId:type_name -> pb.ChatChannel
	18, // 8: pb.LS2C_SendChatMessageRes.message:type_name -> pb.BroadMessage
	19, // 9: pb.LS2C_HasReadMessageRes.common_data:type_name -> pb.CliComData
	0,  // 10: pb.LS2C_NotifyMessage.channelId:type_name -> pb.ChatChannel
	18, // 11: pb.LS2C_NotifyMessage.message:type_name -> pb.BroadMessage
	20, // 12: pb.LS2C_NotifyMessage.roleInfo:type_name -> pb.PCommonRoleBaseInfo
	0,  // 13: pb.LS2C_NotifyPrivateMessage.channelId:type_name -> pb.ChatChannel
	18, // 14: pb.LS2C_NotifyPrivateMessage.message:type_name -> pb.BroadMessage
	20, // 15: pb.LS2C_NotifyPrivateMessage.roleInfo:type_name -> pb.PCommonRoleBaseInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_JoinChatRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_JoinChatRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_GetChannelMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_GetChannelMessageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_InvitedFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_InvitedFriendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_PushMessageToUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_PushMessageToUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_GetChatMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_GetChatMessageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_SendChatMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_SendChatMessageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_HasReadMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_HasReadMessageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_NotifyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_NotifyPrivateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllianceMemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_rawDesc = nil
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
