// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: duty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2LS_InitDutyInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2LS_InitDutyInfoReq) Reset() {
	*x = C2LS_InitDutyInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_InitDutyInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_InitDutyInfoReq) ProtoMessage() {}

func (x *C2LS_InitDutyInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_InitDutyInfoReq.ProtoReflect.Descriptor instead.
func (*C2LS_InitDutyInfoReq) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{0}
}

type LS2C_InitDutyInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_InitDutyInfoRes) Reset() {
	*x = LS2C_InitDutyInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_InitDutyInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_InitDutyInfoRes) ProtoMessage() {}

func (x *LS2C_InitDutyInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_InitDutyInfoRes.ProtoReflect.Descriptor instead.
func (*LS2C_InitDutyInfoRes) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_InitDutyInfoRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type C2LS_ChangeDutyCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId int32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *C2LS_ChangeDutyCardReq) Reset() {
	*x = C2LS_ChangeDutyCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ChangeDutyCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ChangeDutyCardReq) ProtoMessage() {}

func (x *C2LS_ChangeDutyCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ChangeDutyCardReq.ProtoReflect.Descriptor instead.
func (*C2LS_ChangeDutyCardReq) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{2}
}

func (x *C2LS_ChangeDutyCardReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type LS2C_ChangeDutyCardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId int32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *LS2C_ChangeDutyCardRes) Reset() {
	*x = LS2C_ChangeDutyCardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ChangeDutyCardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ChangeDutyCardRes) ProtoMessage() {}

func (x *LS2C_ChangeDutyCardRes) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ChangeDutyCardRes.ProtoReflect.Descriptor instead.
func (*LS2C_ChangeDutyCardRes) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{3}
}

func (x *LS2C_ChangeDutyCardRes) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

// 领取任务奖励
type C2LS_ReceiveDailyTaskRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    int32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // 0 一键领取
	CycleType int32 `protobuf:"varint,2,opt,name=cycle_type,json=cycleType,proto3" json:"cycle_type,omitempty"` // 任务类型  1 日常 2 周长
}

func (x *C2LS_ReceiveDailyTaskRewardReq) Reset() {
	*x = C2LS_ReceiveDailyTaskRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ReceiveDailyTaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ReceiveDailyTaskRewardReq) ProtoMessage() {}

func (x *C2LS_ReceiveDailyTaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ReceiveDailyTaskRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_ReceiveDailyTaskRewardReq) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{4}
}

func (x *C2LS_ReceiveDailyTaskRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *C2LS_ReceiveDailyTaskRewardReq) GetCycleType() int32 {
	if x != nil {
		return x.CycleType
	}
	return 0
}

type LS2C_ReceiveDailyTaskRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     []int32         `protobuf:"varint,1,rep,packed,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommonData *CliComData     `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	Active     *ActiveInfoItem `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"` // 活跃度信息
	DropChange *DropChange     `protobuf:"bytes,4,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
}

func (x *LS2C_ReceiveDailyTaskRewardRes) Reset() {
	*x = LS2C_ReceiveDailyTaskRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ReceiveDailyTaskRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ReceiveDailyTaskRewardRes) ProtoMessage() {}

func (x *LS2C_ReceiveDailyTaskRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ReceiveDailyTaskRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_ReceiveDailyTaskRewardRes) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{5}
}

func (x *LS2C_ReceiveDailyTaskRewardRes) GetTaskId() []int32 {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *LS2C_ReceiveDailyTaskRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_ReceiveDailyTaskRewardRes) GetActive() *ActiveInfoItem {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *LS2C_ReceiveDailyTaskRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

// 领取活跃度奖励
type C2LS_ReceiveActiveRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveNode int32 `protobuf:"varint,1,opt,name=active_node,json=activeNode,proto3" json:"active_node,omitempty"` // 活跃度节点值
	ActiveType int32 `protobuf:"varint,2,opt,name=active_type,json=activeType,proto3" json:"active_type,omitempty"` // 活跃度类型（1=每日，2=每周）
}

func (x *C2LS_ReceiveActiveRewardReq) Reset() {
	*x = C2LS_ReceiveActiveRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ReceiveActiveRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ReceiveActiveRewardReq) ProtoMessage() {}

func (x *C2LS_ReceiveActiveRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ReceiveActiveRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_ReceiveActiveRewardReq) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{6}
}

func (x *C2LS_ReceiveActiveRewardReq) GetActiveNode() int32 {
	if x != nil {
		return x.ActiveNode
	}
	return 0
}

func (x *C2LS_ReceiveActiveRewardReq) GetActiveType() int32 {
	if x != nil {
		return x.ActiveType
	}
	return 0
}

type LS2C_ReceiveActiveRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData     `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	Active     *ActiveInfoItem `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"` // 活跃度信息
	DropChange *DropChange     `protobuf:"bytes,3,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
}

func (x *LS2C_ReceiveActiveRewardRes) Reset() {
	*x = LS2C_ReceiveActiveRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_duty_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ReceiveActiveRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ReceiveActiveRewardRes) ProtoMessage() {}

func (x *LS2C_ReceiveActiveRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_duty_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ReceiveActiveRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_ReceiveActiveRewardRes) Descriptor() ([]byte, []int) {
	return file_duty_proto_rawDescGZIP(), []int{7}
}

func (x *LS2C_ReceiveActiveRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_ReceiveActiveRewardRes) GetActive() *ActiveInfoItem {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *LS2C_ReceiveActiveRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

var File_duty_proto protoreflect.FileDescriptor

var file_duty_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x75, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x49,
	0x6e, 0x69, 0x74, 0x44, 0x75, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x47,
	0x0a, 0x14, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x75, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x75, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x16, 0x4c, 0x53,
	0x32, 0x43, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x75, 0x74, 0x79, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x58, 0x0a,
	0x1e, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x1e, 0x4c, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x22, 0x5f, 0x0a, 0x1b, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xaa, 0x01, 0x0a, 0x1b, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2e,
	0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_duty_proto_rawDescOnce sync.Once
	file_duty_proto_rawDescData = file_duty_proto_rawDesc
)

func file_duty_proto_rawDescGZIP() []byte {
	file_duty_proto_rawDescOnce.Do(func() {
		file_duty_proto_rawDescData = protoimpl.X.CompressGZIP(file_duty_proto_rawDescData)
	})
	return file_duty_proto_rawDescData
}

var file_duty_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_duty_proto_goTypes = []interface{}{
	(*C2LS_InitDutyInfoReq)(nil),           // 0: pb.C2LS_InitDutyInfoReq
	(*LS2C_InitDutyInfoRes)(nil),           // 1: pb.LS2C_InitDutyInfoRes
	(*C2LS_ChangeDutyCardReq)(nil),         // 2: pb.C2LS_ChangeDutyCardReq
	(*LS2C_ChangeDutyCardRes)(nil),         // 3: pb.LS2C_ChangeDutyCardRes
	(*C2LS_ReceiveDailyTaskRewardReq)(nil), // 4: pb.C2LS_ReceiveDailyTaskRewardReq
	(*LS2C_ReceiveDailyTaskRewardRes)(nil), // 5: pb.LS2C_ReceiveDailyTaskRewardRes
	(*C2LS_ReceiveActiveRewardReq)(nil),    // 6: pb.C2LS_ReceiveActiveRewardReq
	(*LS2C_ReceiveActiveRewardRes)(nil),    // 7: pb.LS2C_ReceiveActiveRewardRes
	(*CliComData)(nil),                     // 8: pb.CliComData
	(*ActiveInfoItem)(nil),                 // 9: pb.ActiveInfoItem
	(*DropChange)(nil),                     // 10: pb.DropChange
}
var file_duty_proto_depIdxs = []int32{
	8,  // 0: pb.LS2C_InitDutyInfoRes.common_data:type_name -> pb.CliComData
	8,  // 1: pb.LS2C_ReceiveDailyTaskRewardRes.common_data:type_name -> pb.CliComData
	9,  // 2: pb.LS2C_ReceiveDailyTaskRewardRes.active:type_name -> pb.ActiveInfoItem
	10, // 3: pb.LS2C_ReceiveDailyTaskRewardRes.dropChange:type_name -> pb.DropChange
	8,  // 4: pb.LS2C_ReceiveActiveRewardRes.common_data:type_name -> pb.CliComData
	9,  // 5: pb.LS2C_ReceiveActiveRewardRes.active:type_name -> pb.ActiveInfoItem
	10, // 6: pb.LS2C_ReceiveActiveRewardRes.dropChange:type_name -> pb.DropChange
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_duty_proto_init() }
func file_duty_proto_init() {
	if File_duty_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_duty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_InitDutyInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_InitDutyInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ChangeDutyCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ChangeDutyCardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ReceiveDailyTaskRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ReceiveDailyTaskRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ReceiveActiveRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_duty_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ReceiveActiveRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_duty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duty_proto_goTypes,
		DependencyIndexes: file_duty_proto_depIdxs,
		MessageInfos:      file_duty_proto_msgTypes,
	}.Build()
	File_duty_proto = out.File
	file_duty_proto_rawDesc = nil
	file_duty_proto_goTypes = nil
	file_duty_proto_depIdxs = nil
}
