// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------服务间调用
// 删除好友
type S2S_DelFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *S2S_DelFriendReq) Reset() {
	*x = S2S_DelFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_DelFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_DelFriendReq) ProtoMessage() {}

func (x *S2S_DelFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_DelFriendReq.ProtoReflect.Descriptor instead.
func (*S2S_DelFriendReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *S2S_DelFriendReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type S2S_DelFriendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_DelFriendRes) Reset() {
	*x = S2S_DelFriendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_DelFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_DelFriendRes) ProtoMessage() {}

func (x *S2S_DelFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_DelFriendRes.ProtoReflect.Descriptor instead.
func (*S2S_DelFriendRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

// 添加申请
type S2S_AddFriendApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *S2S_AddFriendApplyReq) Reset() {
	*x = S2S_AddFriendApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_AddFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_AddFriendApplyReq) ProtoMessage() {}

func (x *S2S_AddFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_AddFriendApplyReq.ProtoReflect.Descriptor instead.
func (*S2S_AddFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *S2S_AddFriendApplyReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type S2S_AddFriendApplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_AddFriendApplyRes) Reset() {
	*x = S2S_AddFriendApplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_AddFriendApplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_AddFriendApplyRes) ProtoMessage() {}

func (x *S2S_AddFriendApplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_AddFriendApplyRes.ProtoReflect.Descriptor instead.
func (*S2S_AddFriendApplyRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

// 同意申请
type S2S_AgreeFriendApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *S2S_AgreeFriendApplyReq) Reset() {
	*x = S2S_AgreeFriendApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_AgreeFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_AgreeFriendApplyReq) ProtoMessage() {}

func (x *S2S_AgreeFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_AgreeFriendApplyReq.ProtoReflect.Descriptor instead.
func (*S2S_AgreeFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{4}
}

func (x *S2S_AgreeFriendApplyReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type S2S_AgreeFriendApplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_AgreeFriendApplyRes) Reset() {
	*x = S2S_AgreeFriendApplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_AgreeFriendApplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_AgreeFriendApplyRes) ProtoMessage() {}

func (x *S2S_AgreeFriendApplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_AgreeFriendApplyRes.ProtoReflect.Descriptor instead.
func (*S2S_AgreeFriendApplyRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{5}
}

// 友情点赠送
type S2S_SendFriendPointReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *S2S_SendFriendPointReq) Reset() {
	*x = S2S_SendFriendPointReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_SendFriendPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_SendFriendPointReq) ProtoMessage() {}

func (x *S2S_SendFriendPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_SendFriendPointReq.ProtoReflect.Descriptor instead.
func (*S2S_SendFriendPointReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{6}
}

func (x *S2S_SendFriendPointReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type S2S_SendFriendPointRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_SendFriendPointRes) Reset() {
	*x = S2S_SendFriendPointRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_SendFriendPointRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_SendFriendPointRes) ProtoMessage() {}

func (x *S2S_SendFriendPointRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_SendFriendPointRes.ProtoReflect.Descriptor instead.
func (*S2S_SendFriendPointRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{7}
}

// -----------客户端交互
// 拉取好友列表
type C2LS_GetFriendListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2LS_GetFriendListReq) Reset() {
	*x = C2LS_GetFriendListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_GetFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_GetFriendListReq) ProtoMessage() {}

func (x *C2LS_GetFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_GetFriendListReq.ProtoReflect.Descriptor instead.
func (*C2LS_GetFriendListReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{8}
}

type LS2C_GetFriendListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends *PClientFriendInfo `protobuf:"bytes,1,opt,name=friends,proto3" json:"friends,omitempty"` // 好友数据
}

func (x *LS2C_GetFriendListRes) Reset() {
	*x = LS2C_GetFriendListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_GetFriendListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_GetFriendListRes) ProtoMessage() {}

func (x *LS2C_GetFriendListRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_GetFriendListRes.ProtoReflect.Descriptor instead.
func (*LS2C_GetFriendListRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{9}
}

func (x *LS2C_GetFriendListRes) GetFriends() *PClientFriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

// 添加申请
type C2LS_AddFriendApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 玩家角色id
}

func (x *C2LS_AddFriendApplyReq) Reset() {
	*x = C2LS_AddFriendApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_AddFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_AddFriendApplyReq) ProtoMessage() {}

func (x *C2LS_AddFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_AddFriendApplyReq.ProtoReflect.Descriptor instead.
func (*C2LS_AddFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{10}
}

func (x *C2LS_AddFriendApplyReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LS2C_AddFriendApplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_AddFriendApplyRes) Reset() {
	*x = LS2C_AddFriendApplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_AddFriendApplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_AddFriendApplyRes) ProtoMessage() {}

func (x *LS2C_AddFriendApplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_AddFriendApplyRes.ProtoReflect.Descriptor instead.
func (*LS2C_AddFriendApplyRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{11}
}

func (x *LS2C_AddFriendApplyRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 处理申请
type C2LS_FriendApplyHandleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleIds uint64 `protobuf:"varint,1,opt,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"` // 玩家id(0 = 一键处理)
	IsAgree bool   `protobuf:"varint,2,opt,name=is_agree,json=isAgree,proto3" json:"is_agree,omitempty"` // 是否同意
}

func (x *C2LS_FriendApplyHandleReq) Reset() {
	*x = C2LS_FriendApplyHandleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_FriendApplyHandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_FriendApplyHandleReq) ProtoMessage() {}

func (x *C2LS_FriendApplyHandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_FriendApplyHandleReq.ProtoReflect.Descriptor instead.
func (*C2LS_FriendApplyHandleReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{12}
}

func (x *C2LS_FriendApplyHandleReq) GetRoleIds() uint64 {
	if x != nil {
		return x.RoleIds
	}
	return 0
}

func (x *C2LS_FriendApplyHandleReq) GetIsAgree() bool {
	if x != nil {
		return x.IsAgree
	}
	return false
}

type LS2C_FriendApplyHandleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleIds    []uint64    `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	IsAgree    bool        `protobuf:"varint,2,opt,name=is_agree,json=isAgree,proto3" json:"is_agree,omitempty"` // 是否同意
	CommonData *CliComData `protobuf:"bytes,3,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_FriendApplyHandleRes) Reset() {
	*x = LS2C_FriendApplyHandleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_FriendApplyHandleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_FriendApplyHandleRes) ProtoMessage() {}

func (x *LS2C_FriendApplyHandleRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_FriendApplyHandleRes.ProtoReflect.Descriptor instead.
func (*LS2C_FriendApplyHandleRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{13}
}

func (x *LS2C_FriendApplyHandleRes) GetRoleIds() []uint64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *LS2C_FriendApplyHandleRes) GetIsAgree() bool {
	if x != nil {
		return x.IsAgree
	}
	return false
}

func (x *LS2C_FriendApplyHandleRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 删除好友
type C2LS_DelFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 删除的玩家id
}

func (x *C2LS_DelFriendReq) Reset() {
	*x = C2LS_DelFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_DelFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_DelFriendReq) ProtoMessage() {}

func (x *C2LS_DelFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_DelFriendReq.ProtoReflect.Descriptor instead.
func (*C2LS_DelFriendReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{14}
}

func (x *C2LS_DelFriendReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LS2C_DelFriendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *LS2C_DelFriendRes) Reset() {
	*x = LS2C_DelFriendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_DelFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_DelFriendRes) ProtoMessage() {}

func (x *LS2C_DelFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_DelFriendRes.ProtoReflect.Descriptor instead.
func (*LS2C_DelFriendRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{15}
}

func (x *LS2C_DelFriendRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 黑名单操作
type C2LS_BlackOperateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Operate int32  `protobuf:"varint,2,opt,name=operate,proto3" json:"operate,omitempty"` // 1=加入，2=移除
}

func (x *C2LS_BlackOperateReq) Reset() {
	*x = C2LS_BlackOperateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_BlackOperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_BlackOperateReq) ProtoMessage() {}

func (x *C2LS_BlackOperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_BlackOperateReq.ProtoReflect.Descriptor instead.
func (*C2LS_BlackOperateReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{16}
}

func (x *C2LS_BlackOperateReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2LS_BlackOperateReq) GetOperate() int32 {
	if x != nil {
		return x.Operate
	}
	return 0
}

type LS2C_BlackOperateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info    *PCommonRoleBaseInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Operate int32                `protobuf:"varint,2,opt,name=operate,proto3" json:"operate,omitempty"`
	RoleId  uint64               `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *LS2C_BlackOperateRes) Reset() {
	*x = LS2C_BlackOperateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_BlackOperateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_BlackOperateRes) ProtoMessage() {}

func (x *LS2C_BlackOperateRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_BlackOperateRes.ProtoReflect.Descriptor instead.
func (*LS2C_BlackOperateRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{17}
}

func (x *LS2C_BlackOperateRes) GetInfo() *PCommonRoleBaseInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *LS2C_BlackOperateRes) GetOperate() int32 {
	if x != nil {
		return x.Operate
	}
	return 0
}

func (x *LS2C_BlackOperateRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 好友推荐
type C2LS_GetFriendRecommendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2LS_GetFriendRecommendReq) Reset() {
	*x = C2LS_GetFriendRecommendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_GetFriendRecommendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_GetFriendRecommendReq) ProtoMessage() {}

func (x *C2LS_GetFriendRecommendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_GetFriendRecommendReq.ProtoReflect.Descriptor instead.
func (*C2LS_GetFriendRecommendReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{18}
}

type LS2C_GetFriendRecommendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleList    []*PCommonRoleBaseInfo `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
	RecommendTs int64                  `protobuf:"varint,2,opt,name=recommend_ts,json=recommendTs,proto3" json:"recommend_ts,omitempty"` // 好友推荐刷新时间
}

func (x *LS2C_GetFriendRecommendRes) Reset() {
	*x = LS2C_GetFriendRecommendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_GetFriendRecommendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_GetFriendRecommendRes) ProtoMessage() {}

func (x *LS2C_GetFriendRecommendRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_GetFriendRecommendRes.ProtoReflect.Descriptor instead.
func (*LS2C_GetFriendRecommendRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{19}
}

func (x *LS2C_GetFriendRecommendRes) GetRoleList() []*PCommonRoleBaseInfo {
	if x != nil {
		return x.RoleList
	}
	return nil
}

func (x *LS2C_GetFriendRecommendRes) GetRecommendTs() int64 {
	if x != nil {
		return x.RecommendTs
	}
	return 0
}

// 访问露营地
type C2LS_GetFriendCampReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *C2LS_GetFriendCampReq) Reset() {
	*x = C2LS_GetFriendCampReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_GetFriendCampReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_GetFriendCampReq) ProtoMessage() {}

func (x *C2LS_GetFriendCampReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_GetFriendCampReq.ProtoReflect.Descriptor instead.
func (*C2LS_GetFriendCampReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{20}
}

func (x *C2LS_GetFriendCampReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LS2C_GetFriendCampRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camp    *PFriendCampInfo `protobuf:"bytes,1,opt,name=camp,proto3" json:"camp,omitempty"`
	RoleId  uint64           `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ErrCode int32            `protobuf:"varint,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"` // 用于前端显示错误文本 （0=成功, 1=对方不是好友）
}

func (x *LS2C_GetFriendCampRes) Reset() {
	*x = LS2C_GetFriendCampRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_GetFriendCampRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_GetFriendCampRes) ProtoMessage() {}

func (x *LS2C_GetFriendCampRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_GetFriendCampRes.ProtoReflect.Descriptor instead.
func (*LS2C_GetFriendCampRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{21}
}

func (x *LS2C_GetFriendCampRes) GetCamp() *PFriendCampInfo {
	if x != nil {
		return x.Camp
	}
	return nil
}

func (x *LS2C_GetFriendCampRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LS2C_GetFriendCampRes) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

// 友情点操作
type C2LS_OperateFriendPointReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleIds uint64 `protobuf:"varint,1,opt,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"` // 目标列表(赠送或者领取单个，0为一键领取+赠送)
	Operate int32  `protobuf:"varint,2,opt,name=operate,proto3" json:"operate,omitempty"`                // 1=赠送，2=收取
}

func (x *C2LS_OperateFriendPointReq) Reset() {
	*x = C2LS_OperateFriendPointReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_OperateFriendPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_OperateFriendPointReq) ProtoMessage() {}

func (x *C2LS_OperateFriendPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_OperateFriendPointReq.ProtoReflect.Descriptor instead.
func (*C2LS_OperateFriendPointReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{22}
}

func (x *C2LS_OperateFriendPointReq) GetRoleIds() uint64 {
	if x != nil {
		return x.RoleIds
	}
	return 0
}

func (x *C2LS_OperateFriendPointReq) GetOperate() int32 {
	if x != nil {
		return x.Operate
	}
	return 0
}

type LS2C_OperateFriendPointRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendIds    []uint64    `protobuf:"varint,1,rep,packed,name=send_ids,json=sendIds,proto3" json:"send_ids,omitempty"`          // 赠送成功列表
	ReceiveIds []uint64    `protobuf:"varint,2,rep,packed,name=receive_ids,json=receiveIds,proto3" json:"receive_ids,omitempty"` // 领取成功列表
	DropChange *DropChange `protobuf:"bytes,3,opt,name=dropChange,proto3" json:"dropChange,omitempty"`                           // 友情点弹窗
	CommonData *CliComData `protobuf:"bytes,4,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	DelIds     []uint64    `protobuf:"varint,5,rep,packed,name=del_ids,json=delIds,proto3" json:"del_ids,omitempty"` // 不是好友的id列表(非空则提示对方不是好友)
}

func (x *LS2C_OperateFriendPointRes) Reset() {
	*x = LS2C_OperateFriendPointRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_OperateFriendPointRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_OperateFriendPointRes) ProtoMessage() {}

func (x *LS2C_OperateFriendPointRes) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_OperateFriendPointRes.ProtoReflect.Descriptor instead.
func (*LS2C_OperateFriendPointRes) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{23}
}

func (x *LS2C_OperateFriendPointRes) GetSendIds() []uint64 {
	if x != nil {
		return x.SendIds
	}
	return nil
}

func (x *LS2C_OperateFriendPointRes) GetReceiveIds() []uint64 {
	if x != nil {
		return x.ReceiveIds
	}
	return nil
}

func (x *LS2C_OperateFriendPointRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

func (x *LS2C_OperateFriendPointRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_OperateFriendPointRes) GetDelIds() []uint64 {
	if x != nil {
		return x.DelIds
	}
	return nil
}

var File_friend_proto protoreflect.FileDescriptor

var file_friend_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x10, 0x53, 0x32, 0x53, 0x5f,
	0x44, 0x65, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x6c,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x15, 0x53, 0x32, 0x53,
	0x5f, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x53,
	0x32, 0x53, 0x5f, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x17, 0x53, 0x32, 0x53, 0x5f, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x32, 0x53, 0x5f,
	0x41, 0x67, 0x72, 0x65, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x53, 0x32, 0x53, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x32, 0x53, 0x5f, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x22, 0x17, 0x0a, 0x15, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x48, 0x0a, 0x15, 0x4c, 0x53, 0x32,
	0x43, 0x5f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x41, 0x64, 0x64, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x51, 0x0a, 0x19, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f,
	0x61, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41,
	0x67, 0x72, 0x65, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x19, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x73, 0x5f, 0x61, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x41, 0x67, 0x72, 0x65, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x32, 0x4c,
	0x53, 0x5f, 0x44, 0x65, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x44, 0x65, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x14, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x22, 0x76, 0x0a, 0x14, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x32, 0x4c, 0x53,
	0x5f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x22, 0x75, 0x0a, 0x1a, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x47,
	0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x22, 0x30, 0x0a,
	0x15, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x43,
	0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x74, 0x0a, 0x15, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x43, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x63, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x43, 0x61, 0x6d, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x63, 0x61, 0x6d,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x51, 0x0a, 0x1a, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x1a, 0x4c, 0x53, 0x32,
	0x43, 0x5f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x49,
	0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x72, 0x6f,
	0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x73, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData = file_friend_proto_rawDesc
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_friend_proto_rawDescData)
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_friend_proto_goTypes = []interface{}{
	(*S2S_DelFriendReq)(nil),           // 0: pb.S2S_DelFriendReq
	(*S2S_DelFriendRes)(nil),           // 1: pb.S2S_DelFriendRes
	(*S2S_AddFriendApplyReq)(nil),      // 2: pb.S2S_AddFriendApplyReq
	(*S2S_AddFriendApplyRes)(nil),      // 3: pb.S2S_AddFriendApplyRes
	(*S2S_AgreeFriendApplyReq)(nil),    // 4: pb.S2S_AgreeFriendApplyReq
	(*S2S_AgreeFriendApplyRes)(nil),    // 5: pb.S2S_AgreeFriendApplyRes
	(*S2S_SendFriendPointReq)(nil),     // 6: pb.S2S_SendFriendPointReq
	(*S2S_SendFriendPointRes)(nil),     // 7: pb.S2S_SendFriendPointRes
	(*C2LS_GetFriendListReq)(nil),      // 8: pb.C2LS_GetFriendListReq
	(*LS2C_GetFriendListRes)(nil),      // 9: pb.LS2C_GetFriendListRes
	(*C2LS_AddFriendApplyReq)(nil),     // 10: pb.C2LS_AddFriendApplyReq
	(*LS2C_AddFriendApplyRes)(nil),     // 11: pb.LS2C_AddFriendApplyRes
	(*C2LS_FriendApplyHandleReq)(nil),  // 12: pb.C2LS_FriendApplyHandleReq
	(*LS2C_FriendApplyHandleRes)(nil),  // 13: pb.LS2C_FriendApplyHandleRes
	(*C2LS_DelFriendReq)(nil),          // 14: pb.C2LS_DelFriendReq
	(*LS2C_DelFriendRes)(nil),          // 15: pb.LS2C_DelFriendRes
	(*C2LS_BlackOperateReq)(nil),       // 16: pb.C2LS_BlackOperateReq
	(*LS2C_BlackOperateRes)(nil),       // 17: pb.LS2C_BlackOperateRes
	(*C2LS_GetFriendRecommendReq)(nil), // 18: pb.C2LS_GetFriendRecommendReq
	(*LS2C_GetFriendRecommendRes)(nil), // 19: pb.LS2C_GetFriendRecommendRes
	(*C2LS_GetFriendCampReq)(nil),      // 20: pb.C2LS_GetFriendCampReq
	(*LS2C_GetFriendCampRes)(nil),      // 21: pb.LS2C_GetFriendCampRes
	(*C2LS_OperateFriendPointReq)(nil), // 22: pb.C2LS_OperateFriendPointReq
	(*LS2C_OperateFriendPointRes)(nil), // 23: pb.LS2C_OperateFriendPointRes
	(*PClientFriendInfo)(nil),          // 24: pb.PClientFriendInfo
	(*CliComData)(nil),                 // 25: pb.CliComData
	(*PCommonRoleBaseInfo)(nil),        // 26: pb.PCommonRoleBaseInfo
	(*PFriendCampInfo)(nil),            // 27: pb.PFriendCampInfo
	(*DropChange)(nil),                 // 28: pb.DropChange
}
var file_friend_proto_depIdxs = []int32{
	24, // 0: pb.LS2C_GetFriendListRes.friends:type_name -> pb.PClientFriendInfo
	25, // 1: pb.LS2C_AddFriendApplyRes.common_data:type_name -> pb.CliComData
	25, // 2: pb.LS2C_FriendApplyHandleRes.common_data:type_name -> pb.CliComData
	26, // 3: pb.LS2C_BlackOperateRes.info:type_name -> pb.PCommonRoleBaseInfo
	26, // 4: pb.LS2C_GetFriendRecommendRes.role_list:type_name -> pb.PCommonRoleBaseInfo
	27, // 5: pb.LS2C_GetFriendCampRes.camp:type_name -> pb.PFriendCampInfo
	28, // 6: pb.LS2C_OperateFriendPointRes.dropChange:type_name -> pb.DropChange
	25, // 7: pb.LS2C_OperateFriendPointRes.common_data:type_name -> pb.CliComData
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_DelFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_DelFriendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_AddFriendApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_AddFriendApplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_AgreeFriendApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_AgreeFriendApplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_SendFriendPointReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_SendFriendPointRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_GetFriendListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_GetFriendListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_AddFriendApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_AddFriendApplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_FriendApplyHandleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_FriendApplyHandleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_DelFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_DelFriendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_BlackOperateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_BlackOperateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_GetFriendRecommendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_GetFriendRecommendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_GetFriendCampReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_GetFriendCampRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_OperateFriendPointReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_OperateFriendPointRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_rawDesc = nil
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
