// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: guide_task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 领取任务奖励
type C2LS_ReceiveGuideTaskRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *C2LS_ReceiveGuideTaskRewardReq) Reset() {
	*x = C2LS_ReceiveGuideTaskRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ReceiveGuideTaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ReceiveGuideTaskRewardReq) ProtoMessage() {}

func (x *C2LS_ReceiveGuideTaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_guide_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ReceiveGuideTaskRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_ReceiveGuideTaskRewardReq) Descriptor() ([]byte, []int) {
	return file_guide_task_proto_rawDescGZIP(), []int{0}
}

func (x *C2LS_ReceiveGuideTaskRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LS2C_ReceiveGuideTaskRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     int32       `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	DropChange *DropChange `protobuf:"bytes,3,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
}

func (x *LS2C_ReceiveGuideTaskRewardRes) Reset() {
	*x = LS2C_ReceiveGuideTaskRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ReceiveGuideTaskRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ReceiveGuideTaskRewardRes) ProtoMessage() {}

func (x *LS2C_ReceiveGuideTaskRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_guide_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ReceiveGuideTaskRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_ReceiveGuideTaskRewardRes) Descriptor() ([]byte, []int) {
	return file_guide_task_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_ReceiveGuideTaskRewardRes) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *LS2C_ReceiveGuideTaskRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_ReceiveGuideTaskRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

var File_guide_task_proto protoreflect.FileDescriptor

var file_guide_task_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x75, 0x69, 0x64, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x1e,
	0x43, 0x32, 0x4c, 0x53, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x47, 0x75, 0x69, 0x64,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x1e, 0x4c, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x72,
	0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guide_task_proto_rawDescOnce sync.Once
	file_guide_task_proto_rawDescData = file_guide_task_proto_rawDesc
)

func file_guide_task_proto_rawDescGZIP() []byte {
	file_guide_task_proto_rawDescOnce.Do(func() {
		file_guide_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_guide_task_proto_rawDescData)
	})
	return file_guide_task_proto_rawDescData
}

var file_guide_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guide_task_proto_goTypes = []interface{}{
	(*C2LS_ReceiveGuideTaskRewardReq)(nil), // 0: pb.C2LS_ReceiveGuideTaskRewardReq
	(*LS2C_ReceiveGuideTaskRewardRes)(nil), // 1: pb.LS2C_ReceiveGuideTaskRewardRes
	(*CliComData)(nil),                     // 2: pb.CliComData
	(*DropChange)(nil),                     // 3: pb.DropChange
}
var file_guide_task_proto_depIdxs = []int32{
	2, // 0: pb.LS2C_ReceiveGuideTaskRewardRes.common_data:type_name -> pb.CliComData
	3, // 1: pb.LS2C_ReceiveGuideTaskRewardRes.dropChange:type_name -> pb.DropChange
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guide_task_proto_init() }
func file_guide_task_proto_init() {
	if File_guide_task_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_guide_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ReceiveGuideTaskRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ReceiveGuideTaskRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guide_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_task_proto_goTypes,
		DependencyIndexes: file_guide_task_proto_depIdxs,
		MessageInfos:      file_guide_task_proto_msgTypes,
	}.Build()
	File_guide_task_proto = out.File
	file_guide_task_proto_rawDesc = nil
	file_guide_task_proto_goTypes = nil
	file_guide_task_proto_depIdxs = nil
}
