// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: hand_book.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1.初始化
type C2LS_InitHandBookInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2LS_InitHandBookInfoReq) Reset() {
	*x = C2LS_InitHandBookInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_InitHandBookInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_InitHandBookInfoReq) ProtoMessage() {}

func (x *C2LS_InitHandBookInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_hand_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_InitHandBookInfoReq.ProtoReflect.Descriptor instead.
func (*C2LS_InitHandBookInfoReq) Descriptor() ([]byte, []int) {
	return file_hand_book_proto_rawDescGZIP(), []int{0}
}

type LS2C_InitHandBookInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*HandBookItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"` // 所有数据dffdfcsxvdas
}

func (x *LS2C_InitHandBookInfoRes) Reset() {
	*x = LS2C_InitHandBookInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_InitHandBookInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_InitHandBookInfoRes) ProtoMessage() {}

func (x *LS2C_InitHandBookInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_hand_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_InitHandBookInfoRes.ProtoReflect.Descriptor instead.
func (*LS2C_InitHandBookInfoRes) Descriptor() ([]byte, []int) {
	return file_hand_book_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_InitHandBookInfoRes) GetItems() []*HandBookItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 2.领取对应的任务奖励
type C2LS_HandBookRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务id
	CardId int32 `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // 卡牌id
}

func (x *C2LS_HandBookRewardReq) Reset() {
	*x = C2LS_HandBookRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_HandBookRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_HandBookRewardReq) ProtoMessage() {}

func (x *C2LS_HandBookRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_hand_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_HandBookRewardReq.ProtoReflect.Descriptor instead.
func (*C2LS_HandBookRewardReq) Descriptor() ([]byte, []int) {
	return file_hand_book_proto_rawDescGZIP(), []int{2}
}

func (x *C2LS_HandBookRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *C2LS_HandBookRewardReq) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

// 响应
type LS2C_HandBookRewardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     int32       `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`            // 任务id
	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"` // 公共数据
	DropChange *DropChange `protobuf:"bytes,3,opt,name=dropChange,proto3" json:"dropChange,omitempty"`
}

func (x *LS2C_HandBookRewardRes) Reset() {
	*x = LS2C_HandBookRewardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hand_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_HandBookRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_HandBookRewardRes) ProtoMessage() {}

func (x *LS2C_HandBookRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_hand_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_HandBookRewardRes.ProtoReflect.Descriptor instead.
func (*LS2C_HandBookRewardRes) Descriptor() ([]byte, []int) {
	return file_hand_book_proto_rawDescGZIP(), []int{3}
}

func (x *LS2C_HandBookRewardRes) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *LS2C_HandBookRewardRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *LS2C_HandBookRewardRes) GetDropChange() *DropChange {
	if x != nil {
		return x.DropChange
	}
	return nil
}

var File_hand_book_proto protoreflect.FileDescriptor

var file_hand_book_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x18, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x43,
	0x32, 0x4c, 0x53, 0x5f, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x42, 0x0a, 0x18, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x49, 0x6e, 0x69, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4a, 0x0a, 0x16, 0x43,
	0x32, 0x4c, 0x53, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43,
	0x5f, 0x48, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x0a,
	0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hand_book_proto_rawDescOnce sync.Once
	file_hand_book_proto_rawDescData = file_hand_book_proto_rawDesc
)

func file_hand_book_proto_rawDescGZIP() []byte {
	file_hand_book_proto_rawDescOnce.Do(func() {
		file_hand_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_hand_book_proto_rawDescData)
	})
	return file_hand_book_proto_rawDescData
}

var file_hand_book_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hand_book_proto_goTypes = []interface{}{
	(*C2LS_InitHandBookInfoReq)(nil), // 0: pb.C2LS_InitHandBookInfoReq
	(*LS2C_InitHandBookInfoRes)(nil), // 1: pb.LS2C_InitHandBookInfoRes
	(*C2LS_HandBookRewardReq)(nil),   // 2: pb.C2LS_HandBookRewardReq
	(*LS2C_HandBookRewardRes)(nil),   // 3: pb.LS2C_HandBookRewardRes
	(*HandBookItem)(nil),             // 4: pb.HandBookItem
	(*CliComData)(nil),               // 5: pb.CliComData
	(*DropChange)(nil),               // 6: pb.DropChange
}
var file_hand_book_proto_depIdxs = []int32{
	4, // 0: pb.LS2C_InitHandBookInfoRes.Items:type_name -> pb.HandBookItem
	5, // 1: pb.LS2C_HandBookRewardRes.common_data:type_name -> pb.CliComData
	6, // 2: pb.LS2C_HandBookRewardRes.dropChange:type_name -> pb.DropChange
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hand_book_proto_init() }
func file_hand_book_proto_init() {
	if File_hand_book_proto != nil {
		return
	}
	file_client_common_data_proto_init()
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hand_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_InitHandBookInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_InitHandBookInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_HandBookRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hand_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_HandBookRewardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hand_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hand_book_proto_goTypes,
		DependencyIndexes: file_hand_book_proto_depIdxs,
		MessageInfos:      file_hand_book_proto_msgTypes,
	}.Build()
	File_hand_book_proto = out.File
	file_hand_book_proto_rawDesc = nil
	file_hand_book_proto_goTypes = nil
	file_hand_book_proto_depIdxs = nil
}
