// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登陆渠道类型
type LoginChannelType int32

const (
	LoginChannelType_LoginChannelType_None LoginChannelType = 0 // 占位符
	LoginChannelType_SS_Game               LoginChannelType = 1 // ss-game
	LoginChannelType_Taptap_Game           LoginChannelType = 2 // taptap
	LoginChannelType_Lilith_Game           LoginChannelType = 3 // 莉莉丝
	LoginChannelType_KuaiBao_Game          LoginChannelType = 4 // 好游快爆
	LoginChannelType_LoginChannelType_Max  LoginChannelType = 7 // 占位符
)

// Enum value maps for LoginChannelType.
var (
	LoginChannelType_name = map[int32]string{
		0: "LoginChannelType_None",
		1: "SS_Game",
		2: "Taptap_Game",
		3: "Lilith_Game",
		4: "KuaiBao_Game",
		7: "LoginChannelType_Max",
	}
	LoginChannelType_value = map[string]int32{
		"LoginChannelType_None": 0,
		"SS_Game":               1,
		"Taptap_Game":           2,
		"Lilith_Game":           3,
		"KuaiBao_Game":          4,
		"LoginChannelType_Max":  7,
	}
)

func (x LoginChannelType) Enum() *LoginChannelType {
	p := new(LoginChannelType)
	*p = x
	return p
}

func (x LoginChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[0].Descriptor()
}

func (LoginChannelType) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[0]
}

func (x LoginChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginChannelType.Descriptor instead.
func (LoginChannelType) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

// 会话认证类型
type SessionAuthType int32

const (
	SessionAuthType_SessionAuthType_None         SessionAuthType = 0 // 占位符
	SessionAuthType_SessionAuthType_Normal       SessionAuthType = 1 // 普通登陆
	SessionAuthType_SessionAuthType_Reconnection SessionAuthType = 2 // 断线重连
	SessionAuthType_SessionAuthType_Max          SessionAuthType = 3 // 占位符
)

// Enum value maps for SessionAuthType.
var (
	SessionAuthType_name = map[int32]string{
		0: "SessionAuthType_None",
		1: "SessionAuthType_Normal",
		2: "SessionAuthType_Reconnection",
		3: "SessionAuthType_Max",
	}
	SessionAuthType_value = map[string]int32{
		"SessionAuthType_None":         0,
		"SessionAuthType_Normal":       1,
		"SessionAuthType_Reconnection": 2,
		"SessionAuthType_Max":          3,
	}
)

func (x SessionAuthType) Enum() *SessionAuthType {
	p := new(SessionAuthType)
	*p = x
	return p
}

func (x SessionAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[1].Descriptor()
}

func (SessionAuthType) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[1]
}

func (x SessionAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionAuthType.Descriptor instead.
func (SessionAuthType) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

// 登陆请求
type C2LS_LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId        string           `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                                                   //  taptap登录类型：传unionId
	AccountPasswd    string           `protobuf:"bytes,2,opt,name=account_passwd,json=accountPasswd,proto3" json:"account_passwd,omitempty"`                                       // taptap登录类型：传access_token
	CliRandomSeed    string           `protobuf:"bytes,3,opt,name=cli_random_seed,json=cliRandomSeed,proto3" json:"cli_random_seed,omitempty"`                                     // rsa 客户端随机值
	Extra            string           `protobuf:"bytes,4,opt,name=Extra,proto3" json:"Extra,omitempty"`                                                                            // 额外数据（taptap类型为json）
	LoginChannelType LoginChannelType `protobuf:"varint,10,opt,name=login_channel_type,json=loginChannelType,proto3,enum=pb.LoginChannelType" json:"login_channel_type,omitempty"` // 登陆渠道类型
	CliDeviceInfo    *CliDeviceInfo   `protobuf:"bytes,11,opt,name=cli_device_info,json=cliDeviceInfo,proto3" json:"cli_device_info,omitempty"`                                    // 设备信息
}

func (x *C2LS_LoginReq) Reset() {
	*x = C2LS_LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_LoginReq) ProtoMessage() {}

func (x *C2LS_LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_LoginReq.ProtoReflect.Descriptor instead.
func (*C2LS_LoginReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *C2LS_LoginReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2LS_LoginReq) GetAccountPasswd() string {
	if x != nil {
		return x.AccountPasswd
	}
	return ""
}

func (x *C2LS_LoginReq) GetCliRandomSeed() string {
	if x != nil {
		return x.CliRandomSeed
	}
	return ""
}

func (x *C2LS_LoginReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *C2LS_LoginReq) GetLoginChannelType() LoginChannelType {
	if x != nil {
		return x.LoginChannelType
	}
	return LoginChannelType_LoginChannelType_None
}

func (x *C2LS_LoginReq) GetCliDeviceInfo() *CliDeviceInfo {
	if x != nil {
		return x.CliDeviceInfo
	}
	return nil
}

// 登陆请求结果
type LS2C_LoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId      string          `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AntiIndulgence *AntiIndulgence `protobuf:"bytes,2,opt,name=anti_indulgence,json=antiIndulgence,proto3" json:"anti_indulgence,omitempty"`
	SessionId      uint64          `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GatewayIp      string          `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayPort    uint32          `protobuf:"varint,5,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	UseRsa         int32           `protobuf:"varint,6,opt,name=use_rsa,json=useRsa,proto3" json:"use_rsa,omitempty"` // 是否启用rsa
	ErrCode        int32           `protobuf:"varint,7,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Token          string          `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`                                        // token
	SrvRandomSeed  string          `protobuf:"bytes,9,opt,name=srv_random_seed,json=srvRandomSeed,proto3" json:"srv_random_seed,omitempty"` // rsa 服务器随机值
	GatewayUrl     string          `protobuf:"bytes,10,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`           // gate http url
}

func (x *LS2C_LoginRes) Reset() {
	*x = LS2C_LoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_LoginRes) ProtoMessage() {}

func (x *LS2C_LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_LoginRes.ProtoReflect.Descriptor instead.
func (*LS2C_LoginRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *LS2C_LoginRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LS2C_LoginRes) GetAntiIndulgence() *AntiIndulgence {
	if x != nil {
		return x.AntiIndulgence
	}
	return nil
}

func (x *LS2C_LoginRes) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *LS2C_LoginRes) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *LS2C_LoginRes) GetGatewayPort() uint32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *LS2C_LoginRes) GetUseRsa() int32 {
	if x != nil {
		return x.UseRsa
	}
	return 0
}

func (x *LS2C_LoginRes) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *LS2C_LoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LS2C_LoginRes) GetSrvRandomSeed() string {
	if x != nil {
		return x.SrvRandomSeed
	}
	return ""
}

func (x *LS2C_LoginRes) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

type AntiIndulgence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier uint32 `protobuf:"varint,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	OnlineTime uint32 `protobuf:"varint,2,opt,name=online_time,json=onlineTime,proto3" json:"online_time,omitempty"`
	IsVisitor  bool   `protobuf:"varint,3,opt,name=is_visitor,json=isVisitor,proto3" json:"is_visitor,omitempty"`
}

func (x *AntiIndulgence) Reset() {
	*x = AntiIndulgence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AntiIndulgence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiIndulgence) ProtoMessage() {}

func (x *AntiIndulgence) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiIndulgence.ProtoReflect.Descriptor instead.
func (*AntiIndulgence) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *AntiIndulgence) GetIdentifier() uint32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *AntiIndulgence) GetOnlineTime() uint32 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

func (x *AntiIndulgence) GetIsVisitor() bool {
	if x != nil {
		return x.IsVisitor
	}
	return false
}

// 会话认证请求
type C2DB_SessionAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId   string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionType uint32 `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 详见 enum SessionAuthType
	SessionId   uint64 `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId    string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ticket      int32  `protobuf:"varint,5,opt,name=ticket,proto3" json:"ticket,omitempty"` // 排队门票(没有门票就传:0)
}

func (x *C2DB_SessionAuthReq) Reset() {
	*x = C2DB_SessionAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2DB_SessionAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2DB_SessionAuthReq) ProtoMessage() {}

func (x *C2DB_SessionAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2DB_SessionAuthReq.ProtoReflect.Descriptor instead.
func (*C2DB_SessionAuthReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *C2DB_SessionAuthReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2DB_SessionAuthReq) GetSessionType() uint32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *C2DB_SessionAuthReq) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *C2DB_SessionAuthReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *C2DB_SessionAuthReq) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

type DB2C_SessionAuthRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId   string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SessionType uint32 `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 详见 enum SessionAuthType
	ErrorCode   uint32 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`       // 错误码
	Ticket      int32  `protobuf:"varint,5,opt,name=ticket,proto3" json:"ticket,omitempty"`                              // 排队门票(0:表示可以进入游戏; 其他需要排队)
}

func (x *DB2C_SessionAuthRes) Reset() {
	*x = DB2C_SessionAuthRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB2C_SessionAuthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB2C_SessionAuthRes) ProtoMessage() {}

func (x *DB2C_SessionAuthRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB2C_SessionAuthRes.ProtoReflect.Descriptor instead.
func (*DB2C_SessionAuthRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *DB2C_SessionAuthRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DB2C_SessionAuthRes) GetSessionType() uint32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *DB2C_SessionAuthRes) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *DB2C_SessionAuthRes) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

type GWS2C_GameVersionNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameVersion string `protobuf:"bytes,1,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"` // 游戏版本号
}

func (x *GWS2C_GameVersionNtf) Reset() {
	*x = GWS2C_GameVersionNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWS2C_GameVersionNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWS2C_GameVersionNtf) ProtoMessage() {}

func (x *GWS2C_GameVersionNtf) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWS2C_GameVersionNtf.ProtoReflect.Descriptor instead.
func (*GWS2C_GameVersionNtf) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *GWS2C_GameVersionNtf) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

type DB2LS_PlayerAntiIndulgenceNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	IsVisitor  bool   `protobuf:"varint,2,opt,name=is_visitor,json=isVisitor,proto3" json:"is_visitor,omitempty"`
	Identifier uint32 `protobuf:"varint,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	GameTime   uint32 `protobuf:"varint,4,opt,name=game_time,json=gameTime,proto3" json:"game_time,omitempty"` // 剩余游戏时间
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) Reset() {
	*x = DB2LS_PlayerAntiIndulgenceNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB2LS_PlayerAntiIndulgenceNtf) ProtoMessage() {}

func (x *DB2LS_PlayerAntiIndulgenceNtf) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB2LS_PlayerAntiIndulgenceNtf.ProtoReflect.Descriptor instead.
func (*DB2LS_PlayerAntiIndulgenceNtf) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6}
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) GetIsVisitor() bool {
	if x != nil {
		return x.IsVisitor
	}
	return false
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) GetIdentifier() uint32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *DB2LS_PlayerAntiIndulgenceNtf) GetGameTime() uint32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

type GWS2C_KickOutNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // 踢人描述
}

func (x *GWS2C_KickOutNtf) Reset() {
	*x = GWS2C_KickOutNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWS2C_KickOutNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWS2C_KickOutNtf) ProtoMessage() {}

func (x *GWS2C_KickOutNtf) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWS2C_KickOutNtf.ProtoReflect.Descriptor instead.
func (*GWS2C_KickOutNtf) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7}
}

func (x *GWS2C_KickOutNtf) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 修改玩家昵称请求
type C2LS_ChangeNicknameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewNickname string `protobuf:"bytes,1,opt,name=new_nickname,json=newNickname,proto3" json:"new_nickname,omitempty"`
	ItemId      uint64 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 改名卡道具唯一id
}

func (x *C2LS_ChangeNicknameReq) Reset() {
	*x = C2LS_ChangeNicknameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ChangeNicknameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ChangeNicknameReq) ProtoMessage() {}

func (x *C2LS_ChangeNicknameReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ChangeNicknameReq.ProtoReflect.Descriptor instead.
func (*C2LS_ChangeNicknameReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{8}
}

func (x *C2LS_ChangeNicknameReq) GetNewNickname() string {
	if x != nil {
		return x.NewNickname
	}
	return ""
}

func (x *C2LS_ChangeNicknameReq) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type LS2C_ChangeNicknameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string new_nickname = 1;
	CommonData *CliComData `protobuf:"bytes,2,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_ChangeNicknameRes) Reset() {
	*x = LS2C_ChangeNicknameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ChangeNicknameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ChangeNicknameRes) ProtoMessage() {}

func (x *LS2C_ChangeNicknameRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ChangeNicknameRes.ProtoReflect.Descriptor instead.
func (*LS2C_ChangeNicknameRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{9}
}

func (x *LS2C_ChangeNicknameRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 修改玩家头像
type C2LS_ChangeHeadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadId int32 `protobuf:"varint,1,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"` // 头像id
}

func (x *C2LS_ChangeHeadReq) Reset() {
	*x = C2LS_ChangeHeadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ChangeHeadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ChangeHeadReq) ProtoMessage() {}

func (x *C2LS_ChangeHeadReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ChangeHeadReq.ProtoReflect.Descriptor instead.
func (*C2LS_ChangeHeadReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{10}
}

func (x *C2LS_ChangeHeadReq) GetHeadId() int32 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

type LS2C_ChangeHeadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadId int32 `protobuf:"varint,1,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
}

func (x *LS2C_ChangeHeadRes) Reset() {
	*x = LS2C_ChangeHeadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ChangeHeadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ChangeHeadRes) ProtoMessage() {}

func (x *LS2C_ChangeHeadRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ChangeHeadRes.ProtoReflect.Descriptor instead.
func (*LS2C_ChangeHeadRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{11}
}

func (x *LS2C_ChangeHeadRes) GetHeadId() int32 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

// 修改同行卡牌
type C2LS_ChangeShowCardsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []int32 `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
}

func (x *C2LS_ChangeShowCardsReq) Reset() {
	*x = C2LS_ChangeShowCardsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_ChangeShowCardsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_ChangeShowCardsReq) ProtoMessage() {}

func (x *C2LS_ChangeShowCardsReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_ChangeShowCardsReq.ProtoReflect.Descriptor instead.
func (*C2LS_ChangeShowCardsReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{12}
}

func (x *C2LS_ChangeShowCardsReq) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type LS2C_ChangeShowCardsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*PClientCardInfo `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *LS2C_ChangeShowCardsRes) Reset() {
	*x = LS2C_ChangeShowCardsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ChangeShowCardsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ChangeShowCardsRes) ProtoMessage() {}

func (x *LS2C_ChangeShowCardsRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ChangeShowCardsRes.ProtoReflect.Descriptor instead.
func (*LS2C_ChangeShowCardsRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{13}
}

func (x *LS2C_ChangeShowCardsRes) GetCards() []*PClientCardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// 创角信息
type C2LS_CreateRoleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sex      int32  `protobuf:"varint,1,opt,name=sex,proto3" json:"sex,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *C2LS_CreateRoleInfoReq) Reset() {
	*x = C2LS_CreateRoleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_CreateRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_CreateRoleInfoReq) ProtoMessage() {}

func (x *C2LS_CreateRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_CreateRoleInfoReq.ProtoReflect.Descriptor instead.
func (*C2LS_CreateRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{14}
}

func (x *C2LS_CreateRoleInfoReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *C2LS_CreateRoleInfoReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type LS2C_CreateRoleInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_CreateRoleInfoRes) Reset() {
	*x = LS2C_CreateRoleInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_CreateRoleInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_CreateRoleInfoRes) ProtoMessage() {}

func (x *LS2C_CreateRoleInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_CreateRoleInfoRes.ProtoReflect.Descriptor instead.
func (*LS2C_CreateRoleInfoRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{15}
}

func (x *LS2C_CreateRoleInfoRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

// 查找玩家详情
type C2LS_GetRoleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 玩家角色id
}

func (x *C2LS_GetRoleInfoReq) Reset() {
	*x = C2LS_GetRoleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_GetRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_GetRoleInfoReq) ProtoMessage() {}

func (x *C2LS_GetRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_GetRoleInfoReq.ProtoReflect.Descriptor instead.
func (*C2LS_GetRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{16}
}

func (x *C2LS_GetRoleInfoReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LS2C_GetRoleInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *PClientRoleDetailInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *LS2C_GetRoleInfoRes) Reset() {
	*x = LS2C_GetRoleInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_GetRoleInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_GetRoleInfoRes) ProtoMessage() {}

func (x *LS2C_GetRoleInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_GetRoleInfoRes.ProtoReflect.Descriptor instead.
func (*LS2C_GetRoleInfoRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{17}
}

func (x *LS2C_GetRoleInfoRes) GetInfo() *PClientRoleDetailInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 登录排队时，处于第几位
type LS2C_PendingNumNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingNumber int32 `protobuf:"varint,1,opt,name=pending_number,json=pendingNumber,proto3" json:"pending_number,omitempty"`
}

func (x *LS2C_PendingNumNtf) Reset() {
	*x = LS2C_PendingNumNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_PendingNumNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_PendingNumNtf) ProtoMessage() {}

func (x *LS2C_PendingNumNtf) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_PendingNumNtf.ProtoReflect.Descriptor instead.
func (*LS2C_PendingNumNtf) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{18}
}

func (x *LS2C_PendingNumNtf) GetPendingNumber() int32 {
	if x != nil {
		return x.PendingNumber
	}
	return 0
}

// 登录Gate
type C2G_LoginGateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 令牌
}

func (x *C2G_LoginGateReq) Reset() {
	*x = C2G_LoginGateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_LoginGateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_LoginGateReq) ProtoMessage() {}

func (x *C2G_LoginGateReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_LoginGateReq.ProtoReflect.Descriptor instead.
func (*C2G_LoginGateReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{19}
}

func (x *C2G_LoginGateReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2G_LoginGateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type G2C_LoginGateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err_Code int32 `protobuf:"varint,1,opt,name=err_Code,json=errCode,proto3" json:"err_Code,omitempty"` // 错误码
}

func (x *G2C_LoginGateRes) Reset() {
	*x = G2C_LoginGateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_LoginGateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_LoginGateRes) ProtoMessage() {}

func (x *G2C_LoginGateRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_LoginGateRes.ProtoReflect.Descriptor instead.
func (*G2C_LoginGateRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{20}
}

func (x *G2C_LoginGateRes) GetErr_Code() int32 {
	if x != nil {
		return x.Err_Code
	}
	return 0
}

// 登录游戏
type C2G_LoginGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId   string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                  // 令牌
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                              // 版本
	Channel     string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`                              // 渠道
	PkgChannel  string `protobuf:"bytes,5,opt,name=pkg_channel,json=pkgChannel,proto3" json:"pkg_channel,omitempty"`      //包渠道
	DeviceId    string `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`            // 设备id
	Platform    string `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`                            // 平台
	Ticket      int32  `protobuf:"varint,8,opt,name=ticket,proto3" json:"ticket,omitempty"`                               // 排队门票(没有门票就传:0)
	Language    string `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`                            // 语言版本
	IsReconnect int32  `protobuf:"varint,10,opt,name=is_reconnect,json=isReconnect,proto3" json:"is_reconnect,omitempty"` // 是否是重连(1:是; 0 不是)
}

func (x *C2G_LoginGameReq) Reset() {
	*x = C2G_LoginGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_LoginGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_LoginGameReq) ProtoMessage() {}

func (x *C2G_LoginGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_LoginGameReq.ProtoReflect.Descriptor instead.
func (*C2G_LoginGameReq) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{21}
}

func (x *C2G_LoginGameReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2G_LoginGameReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2G_LoginGameReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *C2G_LoginGameReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *C2G_LoginGameReq) GetPkgChannel() string {
	if x != nil {
		return x.PkgChannel
	}
	return ""
}

func (x *C2G_LoginGameReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *C2G_LoginGameReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *C2G_LoginGameReq) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *C2G_LoginGameReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *C2G_LoginGameReq) GetIsReconnect() int32 {
	if x != nil {
		return x.IsReconnect
	}
	return 0
}

type G2C_LoginGameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err_Code        int32       `protobuf:"varint,1,opt,name=err_Code,json=errCode,proto3" json:"err_Code,omitempty"`                         // 错误码
	RoleId          uint64      `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                            // 角色ID
	Ticket          int32       `protobuf:"varint,3,opt,name=ticket,proto3" json:"ticket,omitempty"`                                          // 排队门票(0:表示可以进入游戏; 其他需要排队)
	ServerTimestamp int64       `protobuf:"varint,4,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"` // 服务器时间戳
	CommonData      *CliComData `protobuf:"bytes,5,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	OrderInfo       *OrderInfo  `protobuf:"bytes,6,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	LevelId         int32       `protobuf:"varint,10,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"` // >0: 在副本中; =0: 不在副本中
}

func (x *G2C_LoginGameRes) Reset() {
	*x = G2C_LoginGameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_LoginGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_LoginGameRes) ProtoMessage() {}

func (x *G2C_LoginGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_LoginGameRes.ProtoReflect.Descriptor instead.
func (*G2C_LoginGameRes) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{22}
}

func (x *G2C_LoginGameRes) GetErr_Code() int32 {
	if x != nil {
		return x.Err_Code
	}
	return 0
}

func (x *G2C_LoginGameRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2C_LoginGameRes) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *G2C_LoginGameRes) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *G2C_LoginGameRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *G2C_LoginGameRes) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *G2C_LoginGameRes) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

type CliDeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idfa        string `protobuf:"bytes,1,opt,name=idfa,proto3" json:"idfa,omitempty"`                                  // ios设备广告标识符
	AndroidId   string `protobuf:"bytes,2,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`       // 安卓设备id
	GoogleAid   string `protobuf:"bytes,3,opt,name=google_aid,json=googleAid,proto3" json:"google_aid,omitempty"`       // Google广告平台账号
	Ip          string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                      // IP地址
	Os          string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`                                      // 玩家设备系统
	OsVersion   string `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`       // 系统版本号
	AppVersion  string `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`    // 应用版本号
	DeviceModel string `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"` // 设备产品型号
	Channel     string `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"`                            // 分发渠道
	Pkg         string `protobuf:"bytes,10,opt,name=pkg,proto3" json:"pkg,omitempty"`                                   // 逻辑包名
	Width       int32  `protobuf:"varint,20,opt,name=width,proto3" json:"width,omitempty"`                              // 屏幕宽度
	Height      int32  `protobuf:"varint,21,opt,name=height,proto3" json:"height,omitempty"`                            // 屏幕高度
	Network     int32  `protobuf:"varint,22,opt,name=network,proto3" json:"network,omitempty"`                          // 网络类型 WiFi传入2，未知传入3，2G传入4，3G传入5，4G传入6
}

func (x *CliDeviceInfo) Reset() {
	*x = CliDeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CliDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliDeviceInfo) ProtoMessage() {}

func (x *CliDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliDeviceInfo.ProtoReflect.Descriptor instead.
func (*CliDeviceInfo) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{23}
}

func (x *CliDeviceInfo) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *CliDeviceInfo) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *CliDeviceInfo) GetGoogleAid() string {
	if x != nil {
		return x.GoogleAid
	}
	return ""
}

func (x *CliDeviceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CliDeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *CliDeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *CliDeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *CliDeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *CliDeviceInfo) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CliDeviceInfo) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *CliDeviceInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CliDeviceInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CliDeviceInfo) GetNetwork() int32 {
	if x != nil {
		return x.Network
	}
	return 0
}

var File_login_proto protoreflect.FileDescriptor

var file_login_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x0d, 0x43, 0x32, 0x4c, 0x53,
	0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12,
	0x26, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x5f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x65,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x42, 0x0a,
	0x12, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x39, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x63,
	0x6c, 0x69, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xde, 0x02, 0x0a,
	0x0d, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3b, 0x0a,
	0x0f, 0x61, 0x6e, 0x74, 0x69, 0x5f, 0x69, 0x6e, 0x64, 0x75, 0x6c, 0x67, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x74, 0x69,
	0x49, 0x6e, 0x64, 0x75, 0x6c, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x61, 0x6e, 0x74, 0x69,
	0x49, 0x6e, 0x64, 0x75, 0x6c, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x5f, 0x72, 0x73, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x52, 0x73, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x72, 0x76, 0x5f, 0x72, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x72, 0x76, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x70, 0x0a,
	0x0e, 0x41, 0x6e, 0x74, 0x69, 0x49, 0x6e, 0x64, 0x75, 0x6c, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x22,
	0xab, 0x01, 0x0a, 0x13, 0x43, 0x32, 0x44, 0x42, 0x5f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x8e, 0x01,
	0x0a, 0x13, 0x44, 0x42, 0x32, 0x43, 0x5f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x39,
	0x0a, 0x14, 0x47, 0x57, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x74, 0x66, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61,
	0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x94, 0x01, 0x0a, 0x1d, 0x44, 0x42,
	0x32, 0x4c, 0x53, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x6e, 0x74, 0x69, 0x49, 0x6e,
	0x64, 0x75, 0x6c, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x74, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x2a, 0x0a, 0x10, 0x47, 0x57, 0x53, 0x32, 0x43, 0x5f, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75,
	0x74, 0x4e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x16,
	0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65,
	0x77, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a,
	0x12, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x12,
	0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x17, 0x43,
	0x32, 0x4c, 0x53, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x44, 0x0a, 0x17,
	0x4c, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53,
	0x32, 0x43, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x13, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x13, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3b, 0x0a, 0x12, 0x4c,
	0x53, 0x32, 0x43, 0x5f, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x4e, 0x74,
	0x66, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x10, 0x43, 0x32, 0x47, 0x5f,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0xac, 0x02, 0x0a, 0x10, 0x43, 0x32, 0x47, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6b, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6b, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22,
	0x83, 0x02, 0x0a, 0x10, 0x47, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x29, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x49, 0x64, 0x22, 0xd8, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x66, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x64, 0x66, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x5f, 0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x73, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x6b, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2a, 0x88, 0x01, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x53, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x54, 0x61, 0x70, 0x74, 0x61, 0x70, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x4c, 0x69, 0x6c, 0x69, 0x74, 0x68, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x03, 0x12,
	0x10, 0x0a, 0x0c, 0x4b, 0x75, 0x61, 0x69, 0x42, 0x61, 0x6f, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10,
	0x04, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x07, 0x2a, 0x82, 0x01, 0x0a, 0x0f,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x03,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData = file_login_proto_rawDesc
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_proto_rawDescData)
	})
	return file_login_proto_rawDescData
}

var file_login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_login_proto_goTypes = []interface{}{
	(LoginChannelType)(0),                 // 0: pb.LoginChannelType
	(SessionAuthType)(0),                  // 1: pb.SessionAuthType
	(*C2LS_LoginReq)(nil),                 // 2: pb.C2LS_LoginReq
	(*LS2C_LoginRes)(nil),                 // 3: pb.LS2C_LoginRes
	(*AntiIndulgence)(nil),                // 4: pb.AntiIndulgence
	(*C2DB_SessionAuthReq)(nil),           // 5: pb.C2DB_SessionAuthReq
	(*DB2C_SessionAuthRes)(nil),           // 6: pb.DB2C_SessionAuthRes
	(*GWS2C_GameVersionNtf)(nil),          // 7: pb.GWS2C_GameVersionNtf
	(*DB2LS_PlayerAntiIndulgenceNtf)(nil), // 8: pb.DB2LS_PlayerAntiIndulgenceNtf
	(*GWS2C_KickOutNtf)(nil),              // 9: pb.GWS2C_KickOutNtf
	(*C2LS_ChangeNicknameReq)(nil),        // 10: pb.C2LS_ChangeNicknameReq
	(*LS2C_ChangeNicknameRes)(nil),        // 11: pb.LS2C_ChangeNicknameRes
	(*C2LS_ChangeHeadReq)(nil),            // 12: pb.C2LS_ChangeHeadReq
	(*LS2C_ChangeHeadRes)(nil),            // 13: pb.LS2C_ChangeHeadRes
	(*C2LS_ChangeShowCardsReq)(nil),       // 14: pb.C2LS_ChangeShowCardsReq
	(*LS2C_ChangeShowCardsRes)(nil),       // 15: pb.LS2C_ChangeShowCardsRes
	(*C2LS_CreateRoleInfoReq)(nil),        // 16: pb.C2LS_CreateRoleInfoReq
	(*LS2C_CreateRoleInfoRes)(nil),        // 17: pb.LS2C_CreateRoleInfoRes
	(*C2LS_GetRoleInfoReq)(nil),           // 18: pb.C2LS_GetRoleInfoReq
	(*LS2C_GetRoleInfoRes)(nil),           // 19: pb.LS2C_GetRoleInfoRes
	(*LS2C_PendingNumNtf)(nil),            // 20: pb.LS2C_PendingNumNtf
	(*C2G_LoginGateReq)(nil),              // 21: pb.C2G_LoginGateReq
	(*G2C_LoginGateRes)(nil),              // 22: pb.G2C_LoginGateRes
	(*C2G_LoginGameReq)(nil),              // 23: pb.C2G_LoginGameReq
	(*G2C_LoginGameRes)(nil),              // 24: pb.G2C_LoginGameRes
	(*CliDeviceInfo)(nil),                 // 25: pb.CliDeviceInfo
	(*CliComData)(nil),                    // 26: pb.CliComData
	(*PClientCardInfo)(nil),               // 27: pb.PClientCardInfo
	(*PClientRoleDetailInfo)(nil),         // 28: pb.PClientRoleDetailInfo
	(*OrderInfo)(nil),                     // 29: pb.OrderInfo
}
var file_login_proto_depIdxs = []int32{
	0,  // 0: pb.C2LS_LoginReq.login_channel_type:type_name -> pb.LoginChannelType
	25, // 1: pb.C2LS_LoginReq.cli_device_info:type_name -> pb.CliDeviceInfo
	4,  // 2: pb.LS2C_LoginRes.anti_indulgence:type_name -> pb.AntiIndulgence
	26, // 3: pb.LS2C_ChangeNicknameRes.common_data:type_name -> pb.CliComData
	27, // 4: pb.LS2C_ChangeShowCardsRes.cards:type_name -> pb.PClientCardInfo
	26, // 5: pb.LS2C_CreateRoleInfoRes.common_data:type_name -> pb.CliComData
	28, // 6: pb.LS2C_GetRoleInfoRes.info:type_name -> pb.PClientRoleDetailInfo
	26, // 7: pb.G2C_LoginGameRes.common_data:type_name -> pb.CliComData
	29, // 8: pb.G2C_LoginGameRes.order_info:type_name -> pb.OrderInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_LoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AntiIndulgence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2DB_SessionAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB2C_SessionAuthRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWS2C_GameVersionNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB2LS_PlayerAntiIndulgenceNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWS2C_KickOutNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ChangeNicknameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ChangeNicknameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ChangeHeadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ChangeHeadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_ChangeShowCardsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ChangeShowCardsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_CreateRoleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_CreateRoleInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_GetRoleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_GetRoleInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_PendingNumNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_LoginGateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_LoginGateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_LoginGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_LoginGameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CliDeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		EnumInfos:         file_login_proto_enumTypes,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_rawDesc = nil
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
