// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: role.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerBeginnerTutorialType int32

const (
	PlayerBeginnerTutorialType_PlayerBeginnerTutorialType_None     PlayerBeginnerTutorialType = 0 // 占位符
	PlayerBeginnerTutorialType_PlayerBeginnerTutorialType_Master   PlayerBeginnerTutorialType = 1 // 主新手引导教程id
	PlayerBeginnerTutorialType_PlayerBeginnerTutorialType_Function PlayerBeginnerTutorialType = 2 // 功能型新手教程id
	PlayerBeginnerTutorialType_PlayerBeginnerTutorialType_Max      PlayerBeginnerTutorialType = 3 // 占位符
)

// Enum value maps for PlayerBeginnerTutorialType.
var (
	PlayerBeginnerTutorialType_name = map[int32]string{
		0: "PlayerBeginnerTutorialType_None",
		1: "PlayerBeginnerTutorialType_Master",
		2: "PlayerBeginnerTutorialType_Function",
		3: "PlayerBeginnerTutorialType_Max",
	}
	PlayerBeginnerTutorialType_value = map[string]int32{
		"PlayerBeginnerTutorialType_None":     0,
		"PlayerBeginnerTutorialType_Master":   1,
		"PlayerBeginnerTutorialType_Function": 2,
		"PlayerBeginnerTutorialType_Max":      3,
	}
)

func (x PlayerBeginnerTutorialType) Enum() *PlayerBeginnerTutorialType {
	p := new(PlayerBeginnerTutorialType)
	*p = x
	return p
}

func (x PlayerBeginnerTutorialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerBeginnerTutorialType) Descriptor() protoreflect.EnumDescriptor {
	return file_role_proto_enumTypes[0].Descriptor()
}

func (PlayerBeginnerTutorialType) Type() protoreflect.EnumType {
	return &file_role_proto_enumTypes[0]
}

func (x PlayerBeginnerTutorialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerBeginnerTutorialType.Descriptor instead.
func (PlayerBeginnerTutorialType) EnumDescriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

// 查询角色列表
type C2DB_QueryRoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账号id
}

func (x *C2DB_QueryRoleListReq) Reset() {
	*x = C2DB_QueryRoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2DB_QueryRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2DB_QueryRoleListReq) ProtoMessage() {}

func (x *C2DB_QueryRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2DB_QueryRoleListReq.ProtoReflect.Descriptor instead.
func (*C2DB_QueryRoleListReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *C2DB_QueryRoleListReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DB2C_QueryRoleListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *DB2C_QueryRoleListRes) Reset() {
	*x = DB2C_QueryRoleListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB2C_QueryRoleListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB2C_QueryRoleListRes) ProtoMessage() {}

func (x *DB2C_QueryRoleListRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB2C_QueryRoleListRes.ProtoReflect.Descriptor instead.
func (*DB2C_QueryRoleListRes) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *DB2C_QueryRoleListRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type C2DB_CreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RoleName  string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleSex   uint32 `protobuf:"varint,3,opt,name=role_sex,json=roleSex,proto3" json:"role_sex,omitempty"`
	RoleId    uint64 `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *C2DB_CreateRoleReq) Reset() {
	*x = C2DB_CreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2DB_CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2DB_CreateRoleReq) ProtoMessage() {}

func (x *C2DB_CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2DB_CreateRoleReq.ProtoReflect.Descriptor instead.
func (*C2DB_CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *C2DB_CreateRoleReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2DB_CreateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *C2DB_CreateRoleReq) GetRoleSex() uint32 {
	if x != nil {
		return x.RoleSex
	}
	return 0
}

func (x *C2DB_CreateRoleReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type DB2C_CreateRoleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId          uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName        string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CreateTimestamp int64  `protobuf:"varint,3,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
}

func (x *DB2C_CreateRoleRes) Reset() {
	*x = DB2C_CreateRoleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB2C_CreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB2C_CreateRoleRes) ProtoMessage() {}

func (x *DB2C_CreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB2C_CreateRoleRes.ProtoReflect.Descriptor instead.
func (*DB2C_CreateRoleRes) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

func (x *DB2C_CreateRoleRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DB2C_CreateRoleRes) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *DB2C_CreateRoleRes) GetCreateTimestamp() int64 {
	if x != nil {
		return x.CreateTimestamp
	}
	return 0
}

type C2DB_SelectRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RoleId    uint64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *C2DB_SelectRoleReq) Reset() {
	*x = C2DB_SelectRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2DB_SelectRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2DB_SelectRoleReq) ProtoMessage() {}

func (x *C2DB_SelectRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2DB_SelectRoleReq.ProtoReflect.Descriptor instead.
func (*C2DB_SelectRoleReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

func (x *C2DB_SelectRoleReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *C2DB_SelectRoleReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type DB2C_SelectRoleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
	AccountId  string      `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RoleId     uint64      `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *DB2C_SelectRoleRes) Reset() {
	*x = DB2C_SelectRoleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB2C_SelectRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB2C_SelectRoleRes) ProtoMessage() {}

func (x *DB2C_SelectRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB2C_SelectRoleRes.ProtoReflect.Descriptor instead.
func (*DB2C_SelectRoleRes) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5}
}

func (x *DB2C_SelectRoleRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

func (x *DB2C_SelectRoleRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DB2C_SelectRoleRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LS2C_ReadyToEnterGameNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LS2C_ReadyToEnterGameNtf) Reset() {
	*x = LS2C_ReadyToEnterGameNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_ReadyToEnterGameNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_ReadyToEnterGameNtf) ProtoMessage() {}

func (x *LS2C_ReadyToEnterGameNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_ReadyToEnterGameNtf.ProtoReflect.Descriptor instead.
func (*LS2C_ReadyToEnterGameNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6}
}

type LS2C_AddExpNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleLevel uint32 `protobuf:"varint,1,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`
	RoleExp   uint64 `protobuf:"varint,2,opt,name=role_exp,json=roleExp,proto3" json:"role_exp,omitempty"`
}

func (x *LS2C_AddExpNtf) Reset() {
	*x = LS2C_AddExpNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_AddExpNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_AddExpNtf) ProtoMessage() {}

func (x *LS2C_AddExpNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_AddExpNtf.ProtoReflect.Descriptor instead.
func (*LS2C_AddExpNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7}
}

func (x *LS2C_AddExpNtf) GetRoleLevel() uint32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *LS2C_AddExpNtf) GetRoleExp() uint64 {
	if x != nil {
		return x.RoleExp
	}
	return 0
}

type LS2DB_PlayerEnterGameNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ErrorCode uint32 `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *LS2DB_PlayerEnterGameNtf) Reset() {
	*x = LS2DB_PlayerEnterGameNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2DB_PlayerEnterGameNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2DB_PlayerEnterGameNtf) ProtoMessage() {}

func (x *LS2DB_PlayerEnterGameNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2DB_PlayerEnterGameNtf.ProtoReflect.Descriptor instead.
func (*LS2DB_PlayerEnterGameNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8}
}

func (x *LS2DB_PlayerEnterGameNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LS2DB_PlayerEnterGameNtf) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type LS2S_PlayerEnterGameNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName  string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	GatewayId uint64 `protobuf:"varint,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
}

func (x *LS2S_PlayerEnterGameNtf) Reset() {
	*x = LS2S_PlayerEnterGameNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2S_PlayerEnterGameNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2S_PlayerEnterGameNtf) ProtoMessage() {}

func (x *LS2S_PlayerEnterGameNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2S_PlayerEnterGameNtf.ProtoReflect.Descriptor instead.
func (*LS2S_PlayerEnterGameNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9}
}

func (x *LS2S_PlayerEnterGameNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LS2S_PlayerEnterGameNtf) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *LS2S_PlayerEnterGameNtf) GetGatewayId() uint64 {
	if x != nil {
		return x.GatewayId
	}
	return 0
}

type LS2C_PlayerEnterGameNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestamp     int64 `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`               // 服务器当前时间戳 单位： 毫秒
	OpenServerTimestamp int64 `protobuf:"varint,2,opt,name=open_server_timestamp,json=openServerTimestamp,proto3" json:"open_server_timestamp,omitempty"` // 单位： 秒
}

func (x *LS2C_PlayerEnterGameNtf) Reset() {
	*x = LS2C_PlayerEnterGameNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_PlayerEnterGameNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_PlayerEnterGameNtf) ProtoMessage() {}

func (x *LS2C_PlayerEnterGameNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_PlayerEnterGameNtf.ProtoReflect.Descriptor instead.
func (*LS2C_PlayerEnterGameNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10}
}

func (x *LS2C_PlayerEnterGameNtf) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *LS2C_PlayerEnterGameNtf) GetOpenServerTimestamp() int64 {
	if x != nil {
		return x.OpenServerTimestamp
	}
	return 0
}

type LS2C_RoleBaseInfoNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *PClientRoleBaseInfo `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *LS2C_RoleBaseInfoNtf) Reset() {
	*x = LS2C_RoleBaseInfoNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_RoleBaseInfoNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_RoleBaseInfoNtf) ProtoMessage() {}

func (x *LS2C_RoleBaseInfoNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_RoleBaseInfoNtf.ProtoReflect.Descriptor instead.
func (*LS2C_RoleBaseInfoNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11}
}

func (x *LS2C_RoleBaseInfoNtf) GetBase() *PClientRoleBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

type LS2GWS_PlayerEnterGameNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewaySessionId uint64 `protobuf:"varint,1,opt,name=gateway_session_id,json=gatewaySessionId,proto3" json:"gateway_session_id,omitempty"`
	RoleId           uint64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName         string `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
}

func (x *LS2GWS_PlayerEnterGameNtf) Reset() {
	*x = LS2GWS_PlayerEnterGameNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2GWS_PlayerEnterGameNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2GWS_PlayerEnterGameNtf) ProtoMessage() {}

func (x *LS2GWS_PlayerEnterGameNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2GWS_PlayerEnterGameNtf.ProtoReflect.Descriptor instead.
func (*LS2GWS_PlayerEnterGameNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{12}
}

func (x *LS2GWS_PlayerEnterGameNtf) GetGatewaySessionId() uint64 {
	if x != nil {
		return x.GatewaySessionId
	}
	return 0
}

func (x *LS2GWS_PlayerEnterGameNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LS2GWS_PlayerEnterGameNtf) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type C2LS_UseGameCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId uint64   `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 作用目标id
	Cmd      string   `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`                            // 命令名称
	Param    []string `protobuf:"bytes,3,rep,name=param,proto3" json:"param,omitempty"`                        // 命令参数
}

func (x *C2LS_UseGameCommandReq) Reset() {
	*x = C2LS_UseGameCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_UseGameCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_UseGameCommandReq) ProtoMessage() {}

func (x *C2LS_UseGameCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_UseGameCommandReq.ProtoReflect.Descriptor instead.
func (*C2LS_UseGameCommandReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{13}
}

func (x *C2LS_UseGameCommandReq) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *C2LS_UseGameCommandReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *C2LS_UseGameCommandReq) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

type LS2C_UseGameCommandRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonData *CliComData `protobuf:"bytes,1,opt,name=common_data,json=commonData,proto3" json:"common_data,omitempty"`
}

func (x *LS2C_UseGameCommandRes) Reset() {
	*x = LS2C_UseGameCommandRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_UseGameCommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_UseGameCommandRes) ProtoMessage() {}

func (x *LS2C_UseGameCommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_UseGameCommandRes.ProtoReflect.Descriptor instead.
func (*LS2C_UseGameCommandRes) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{14}
}

func (x *LS2C_UseGameCommandRes) GetCommonData() *CliComData {
	if x != nil {
		return x.CommonData
	}
	return nil
}

type LS2DB_PlayerOfflineNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *LS2DB_PlayerOfflineNtf) Reset() {
	*x = LS2DB_PlayerOfflineNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2DB_PlayerOfflineNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2DB_PlayerOfflineNtf) ProtoMessage() {}

func (x *LS2DB_PlayerOfflineNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2DB_PlayerOfflineNtf.ProtoReflect.Descriptor instead.
func (*LS2DB_PlayerOfflineNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{15}
}

func (x *LS2DB_PlayerOfflineNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type C2LS_PlayerBeginnerTutorialAddRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType uint32 `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // 详见 PlayerBeginnerTutorialType
	TutorialId    uint32 `protobuf:"varint,2,opt,name=tutorial_id,json=tutorialId,proto3" json:"tutorial_id,omitempty"`
}

func (x *C2LS_PlayerBeginnerTutorialAddRecordReq) Reset() {
	*x = C2LS_PlayerBeginnerTutorialAddRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_PlayerBeginnerTutorialAddRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_PlayerBeginnerTutorialAddRecordReq) ProtoMessage() {}

func (x *C2LS_PlayerBeginnerTutorialAddRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_PlayerBeginnerTutorialAddRecordReq.ProtoReflect.Descriptor instead.
func (*C2LS_PlayerBeginnerTutorialAddRecordReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{16}
}

func (x *C2LS_PlayerBeginnerTutorialAddRecordReq) GetOperationType() uint32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *C2LS_PlayerBeginnerTutorialAddRecordReq) GetTutorialId() uint32 {
	if x != nil {
		return x.TutorialId
	}
	return 0
}

type LS2C_PlayerBeginnerTutorialAddRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType uint32 `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // 详见 PlayerBeginnerTutorialType
	TutorialId    uint32 `protobuf:"varint,2,opt,name=tutorial_id,json=tutorialId,proto3" json:"tutorial_id,omitempty"`
}

func (x *LS2C_PlayerBeginnerTutorialAddRecordRes) Reset() {
	*x = LS2C_PlayerBeginnerTutorialAddRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_PlayerBeginnerTutorialAddRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_PlayerBeginnerTutorialAddRecordRes) ProtoMessage() {}

func (x *LS2C_PlayerBeginnerTutorialAddRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_PlayerBeginnerTutorialAddRecordRes.ProtoReflect.Descriptor instead.
func (*LS2C_PlayerBeginnerTutorialAddRecordRes) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{17}
}

func (x *LS2C_PlayerBeginnerTutorialAddRecordRes) GetOperationType() uint32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *LS2C_PlayerBeginnerTutorialAddRecordRes) GetTutorialId() uint32 {
	if x != nil {
		return x.TutorialId
	}
	return 0
}

type LS2C_PlayerBeginnerTutorialListNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tutorial *PPlayerBeginnerTutorial `protobuf:"bytes,1,opt,name=tutorial,proto3" json:"tutorial,omitempty"`
}

func (x *LS2C_PlayerBeginnerTutorialListNtf) Reset() {
	*x = LS2C_PlayerBeginnerTutorialListNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_PlayerBeginnerTutorialListNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_PlayerBeginnerTutorialListNtf) ProtoMessage() {}

func (x *LS2C_PlayerBeginnerTutorialListNtf) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_PlayerBeginnerTutorialListNtf.ProtoReflect.Descriptor instead.
func (*LS2C_PlayerBeginnerTutorialListNtf) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{18}
}

func (x *LS2C_PlayerBeginnerTutorialListNtf) GetTutorial() *PPlayerBeginnerTutorial {
	if x != nil {
		return x.Tutorial
	}
	return nil
}

var File_role_proto protoreflect.FileDescriptor

var file_role_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x32, 0x44, 0x42, 0x5f, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x30,
	0x0a, 0x15, 0x44, 0x42, 0x32, 0x43, 0x5f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x84, 0x01, 0x0a, 0x12, 0x43, 0x32, 0x44, 0x42, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x78, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x12, 0x44, 0x42, 0x32, 0x43, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x4c,
	0x0a, 0x12, 0x43, 0x32, 0x44, 0x42, 0x5f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x12,
	0x44, 0x42, 0x32, 0x43, 0x5f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69,
	0x43, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x4c,
	0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x6f, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x4e, 0x74, 0x66, 0x22, 0x4a, 0x0a, 0x0e, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x41, 0x64, 0x64, 0x45, 0x78, 0x70, 0x4e, 0x74, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72,
	0x6f, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65,
	0x45, 0x78, 0x70, 0x22, 0x52, 0x0a, 0x18, 0x4c, 0x53, 0x32, 0x44, 0x42, 0x5f, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x74, 0x66, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6e, 0x0a, 0x17, 0x4c, 0x53, 0x32, 0x53, 0x5f,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x4e,
	0x74, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x17, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x4e,
	0x74, 0x66, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x32, 0x0a,
	0x15, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6f, 0x70,
	0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x43, 0x0a, 0x14, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x74, 0x66, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x19, 0x4c, 0x53, 0x32, 0x47, 0x57, 0x53,
	0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65,
	0x4e, 0x74, 0x66, 0x12, 0x2c, 0x0a, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x10, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x16, 0x43, 0x32, 0x4c, 0x53, 0x5f,
	0x55, 0x73, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x49, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x55,
	0x73, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6f,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x31, 0x0a, 0x16, 0x4c, 0x53, 0x32, 0x44, 0x42, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x74, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x27, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75, 0x74, 0x6f, 0x72,
	0x69, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x27, 0x4c, 0x53, 0x32, 0x43, 0x5f,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75,
	0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x22, 0x4c, 0x53,
	0x32, 0x43, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x74, 0x66,
	0x12, 0x37, 0x0a, 0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52,
	0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2a, 0xb5, 0x01, 0x0a, 0x1a, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75, 0x74, 0x6f,
	0x72, 0x69, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x25, 0x0a,
	0x21, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54,
	0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x22, 0x0a,
	0x1e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x54,
	0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10,
	0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData = file_role_proto_rawDesc
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_proto_rawDescData)
	})
	return file_role_proto_rawDescData
}

var file_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_role_proto_goTypes = []interface{}{
	(PlayerBeginnerTutorialType)(0),                 // 0: pb.PlayerBeginnerTutorialType
	(*C2DB_QueryRoleListReq)(nil),                   // 1: pb.C2DB_QueryRoleListReq
	(*DB2C_QueryRoleListRes)(nil),                   // 2: pb.DB2C_QueryRoleListRes
	(*C2DB_CreateRoleReq)(nil),                      // 3: pb.C2DB_CreateRoleReq
	(*DB2C_CreateRoleRes)(nil),                      // 4: pb.DB2C_CreateRoleRes
	(*C2DB_SelectRoleReq)(nil),                      // 5: pb.C2DB_SelectRoleReq
	(*DB2C_SelectRoleRes)(nil),                      // 6: pb.DB2C_SelectRoleRes
	(*LS2C_ReadyToEnterGameNtf)(nil),                // 7: pb.LS2C_ReadyToEnterGameNtf
	(*LS2C_AddExpNtf)(nil),                          // 8: pb.LS2C_AddExpNtf
	(*LS2DB_PlayerEnterGameNtf)(nil),                // 9: pb.LS2DB_PlayerEnterGameNtf
	(*LS2S_PlayerEnterGameNtf)(nil),                 // 10: pb.LS2S_PlayerEnterGameNtf
	(*LS2C_PlayerEnterGameNtf)(nil),                 // 11: pb.LS2C_PlayerEnterGameNtf
	(*LS2C_RoleBaseInfoNtf)(nil),                    // 12: pb.LS2C_RoleBaseInfoNtf
	(*LS2GWS_PlayerEnterGameNtf)(nil),               // 13: pb.LS2GWS_PlayerEnterGameNtf
	(*C2LS_UseGameCommandReq)(nil),                  // 14: pb.C2LS_UseGameCommandReq
	(*LS2C_UseGameCommandRes)(nil),                  // 15: pb.LS2C_UseGameCommandRes
	(*LS2DB_PlayerOfflineNtf)(nil),                  // 16: pb.LS2DB_PlayerOfflineNtf
	(*C2LS_PlayerBeginnerTutorialAddRecordReq)(nil), // 17: pb.C2LS_PlayerBeginnerTutorialAddRecordReq
	(*LS2C_PlayerBeginnerTutorialAddRecordRes)(nil), // 18: pb.LS2C_PlayerBeginnerTutorialAddRecordRes
	(*LS2C_PlayerBeginnerTutorialListNtf)(nil),      // 19: pb.LS2C_PlayerBeginnerTutorialListNtf
	(*CliComData)(nil),                              // 20: pb.CliComData
	(*PClientRoleBaseInfo)(nil),                     // 21: pb.PClientRoleBaseInfo
	(*PPlayerBeginnerTutorial)(nil),                 // 22: pb.PPlayerBeginnerTutorial
}
var file_role_proto_depIdxs = []int32{
	20, // 0: pb.DB2C_SelectRoleRes.common_data:type_name -> pb.CliComData
	21, // 1: pb.LS2C_RoleBaseInfoNtf.base:type_name -> pb.PClientRoleBaseInfo
	20, // 2: pb.LS2C_UseGameCommandRes.common_data:type_name -> pb.CliComData
	22, // 3: pb.LS2C_PlayerBeginnerTutorialListNtf.tutorial:type_name -> pb.PPlayerBeginnerTutorial
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_base_proto_init()
	file_client_common_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2DB_QueryRoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB2C_QueryRoleListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2DB_CreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB2C_CreateRoleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2DB_SelectRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB2C_SelectRoleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_ReadyToEnterGameNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_AddExpNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2DB_PlayerEnterGameNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2S_PlayerEnterGameNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_PlayerEnterGameNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_RoleBaseInfoNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2GWS_PlayerEnterGameNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_UseGameCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_UseGameCommandRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2DB_PlayerOfflineNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_PlayerBeginnerTutorialAddRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_PlayerBeginnerTutorialAddRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_PlayerBeginnerTutorialListNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		EnumInfos:         file_role_proto_enumTypes,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_rawDesc = nil
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
