// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: tug.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TugState int32

const (
	TugState_ts_None      TugState = 0 // 占位符
	TugState_ts_countDown TugState = 1 // 倒计时中
	TugState_ts_playing   TugState = 2 // 游戏中
	TugState_ts_game_over TugState = 3 // 结算中
	TugState_ts_Max       TugState = 4 // 占位符
)

// Enum value maps for TugState.
var (
	TugState_name = map[int32]string{
		0: "ts_None",
		1: "ts_countDown",
		2: "ts_playing",
		3: "ts_game_over",
		4: "ts_Max",
	}
	TugState_value = map[string]int32{
		"ts_None":      0,
		"ts_countDown": 1,
		"ts_playing":   2,
		"ts_game_over": 3,
		"ts_Max":       4,
	}
)

func (x TugState) Enum() *TugState {
	p := new(TugState)
	*p = x
	return p
}

func (x TugState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TugState) Descriptor() protoreflect.EnumDescriptor {
	return file_tug_proto_enumTypes[0].Descriptor()
}

func (TugState) Type() protoreflect.EnumType {
	return &file_tug_proto_enumTypes[0]
}

func (x TugState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TugState.Descriptor instead.
func (TugState) EnumDescriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{0}
}

// 拔河游戏数据
type Tug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomModel    RoomModel     `protobuf:"varint,1,opt,name=room_model,json=roomModel,proto3,enum=pb.RoomModel" json:"room_model,omitempty"`
	RoomGameInfo *RoomGameInfo `protobuf:"bytes,2,opt,name=room_game_info,json=roomGameInfo,proto3" json:"room_game_info,omitempty"`     // 游戏基础数据
	TugState     TugState      `protobuf:"varint,3,opt,name=tug_state,json=tugState,proto3,enum=pb.TugState" json:"tug_state,omitempty"` // 游戏状态
	TugTick      int32         `protobuf:"varint,4,opt,name=tug_tick,json=tugTick,proto3" json:"tug_tick,omitempty"`                     // 拔河游戏秒数(3+8)
	Scores       []*TugScore   `protobuf:"bytes,5,rep,name=scores,proto3" json:"scores,omitempty"`                                       // 计分
}

func (x *Tug) Reset() {
	*x = Tug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tug_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tug) ProtoMessage() {}

func (x *Tug) ProtoReflect() protoreflect.Message {
	mi := &file_tug_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tug.ProtoReflect.Descriptor instead.
func (*Tug) Descriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{0}
}

func (x *Tug) GetRoomModel() RoomModel {
	if x != nil {
		return x.RoomModel
	}
	return RoomModel_RoomModel_None
}

func (x *Tug) GetRoomGameInfo() *RoomGameInfo {
	if x != nil {
		return x.RoomGameInfo
	}
	return nil
}

func (x *Tug) GetTugState() TugState {
	if x != nil {
		return x.TugState
	}
	return TugState_ts_None
}

func (x *Tug) GetTugTick() int32 {
	if x != nil {
		return x.TugTick
	}
	return 0
}

func (x *Tug) GetScores() []*TugScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type TugScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerUid string `protobuf:"bytes,1,opt,name=player_uid,json=playerUid,proto3" json:"player_uid,omitempty"` // 玩家的角色id
	Score     int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                         // 得分
}

func (x *TugScore) Reset() {
	*x = TugScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tug_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TugScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TugScore) ProtoMessage() {}

func (x *TugScore) ProtoReflect() protoreflect.Message {
	mi := &file_tug_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TugScore.ProtoReflect.Descriptor instead.
func (*TugScore) Descriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{1}
}

func (x *TugScore) GetPlayerUid() string {
	if x != nil {
		return x.PlayerUid
	}
	return ""
}

func (x *TugScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 拔河游戏-点击
type C2LS_TugClickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalClickCount int32 `protobuf:"varint,2,opt,name=total_click_count,json=totalClickCount,proto3" json:"total_click_count,omitempty"` // 总的点击数
}

func (x *C2LS_TugClickReq) Reset() {
	*x = C2LS_TugClickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tug_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2LS_TugClickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2LS_TugClickReq) ProtoMessage() {}

func (x *C2LS_TugClickReq) ProtoReflect() protoreflect.Message {
	mi := &file_tug_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2LS_TugClickReq.ProtoReflect.Descriptor instead.
func (*C2LS_TugClickReq) Descriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{2}
}

func (x *C2LS_TugClickReq) GetTotalClickCount() int32 {
	if x != nil {
		return x.TotalClickCount
	}
	return 0
}

type LS2C_TugClickRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalClickCount int32 `protobuf:"varint,2,opt,name=total_click_count,json=totalClickCount,proto3" json:"total_click_count,omitempty"` // 总的点击数
}

func (x *LS2C_TugClickRes) Reset() {
	*x = LS2C_TugClickRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tug_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_TugClickRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_TugClickRes) ProtoMessage() {}

func (x *LS2C_TugClickRes) ProtoReflect() protoreflect.Message {
	mi := &file_tug_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_TugClickRes.ProtoReflect.Descriptor instead.
func (*LS2C_TugClickRes) Descriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{3}
}

func (x *LS2C_TugClickRes) GetTotalClickCount() int32 {
	if x != nil {
		return x.TotalClickCount
	}
	return 0
}

type LS2C_TugInfoNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TugInfo *Tug `protobuf:"bytes,1,opt,name=tug_info,json=tugInfo,proto3" json:"tug_info,omitempty"` // 游戏数据
}

func (x *LS2C_TugInfoNtf) Reset() {
	*x = LS2C_TugInfoNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tug_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LS2C_TugInfoNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LS2C_TugInfoNtf) ProtoMessage() {}

func (x *LS2C_TugInfoNtf) ProtoReflect() protoreflect.Message {
	mi := &file_tug_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LS2C_TugInfoNtf.ProtoReflect.Descriptor instead.
func (*LS2C_TugInfoNtf) Descriptor() ([]byte, []int) {
	return file_tug_proto_rawDescGZIP(), []int{4}
}

func (x *LS2C_TugInfoNtf) GetTugInfo() *Tug {
	if x != nil {
		return x.TugInfo
	}
	return nil
}

var File_tug_proto protoreflect.FileDescriptor

var file_tug_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x75, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x03,
	0x54, 0x75, 0x67, 0x12, 0x2c, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x36, 0x0a, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x72, 0x6f, 0x6f,
	0x6d, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x09, 0x74, 0x75, 0x67,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x75, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x74, 0x75, 0x67, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x75, 0x67, 0x5f, 0x74, 0x69, 0x63, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x75, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x12,
	0x24, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x75, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x08, 0x54, 0x75, 0x67, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x3e, 0x0a, 0x10, 0x43, 0x32, 0x4c, 0x53, 0x5f, 0x54,
	0x75, 0x67, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x10, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x54,
	0x75, 0x67, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x35, 0x0a, 0x0f, 0x4c, 0x53, 0x32, 0x43, 0x5f, 0x54,
	0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x74, 0x66, 0x12, 0x22, 0x0a, 0x08, 0x74, 0x75, 0x67,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x75, 0x67, 0x52, 0x07, 0x74, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x57, 0x0a,
	0x08, 0x54, 0x75, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x74, 0x73, 0x5f,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x74, 0x73, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x74, 0x73, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x74, 0x73,
	0x5f, 0x4d, 0x61, 0x78, 0x10, 0x04, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tug_proto_rawDescOnce sync.Once
	file_tug_proto_rawDescData = file_tug_proto_rawDesc
)

func file_tug_proto_rawDescGZIP() []byte {
	file_tug_proto_rawDescOnce.Do(func() {
		file_tug_proto_rawDescData = protoimpl.X.CompressGZIP(file_tug_proto_rawDescData)
	})
	return file_tug_proto_rawDescData
}

var file_tug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tug_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tug_proto_goTypes = []interface{}{
	(TugState)(0),            // 0: pb.TugState
	(*Tug)(nil),              // 1: pb.Tug
	(*TugScore)(nil),         // 2: pb.TugScore
	(*C2LS_TugClickReq)(nil), // 3: pb.C2LS_TugClickReq
	(*LS2C_TugClickRes)(nil), // 4: pb.LS2C_TugClickRes
	(*LS2C_TugInfoNtf)(nil),  // 5: pb.LS2C_TugInfoNtf
	(RoomModel)(0),           // 6: pb.RoomModel
	(*RoomGameInfo)(nil),     // 7: pb.RoomGameInfo
}
var file_tug_proto_depIdxs = []int32{
	6, // 0: pb.Tug.room_model:type_name -> pb.RoomModel
	7, // 1: pb.Tug.room_game_info:type_name -> pb.RoomGameInfo
	0, // 2: pb.Tug.tug_state:type_name -> pb.TugState
	2, // 3: pb.Tug.scores:type_name -> pb.TugScore
	1, // 4: pb.LS2C_TugInfoNtf.tug_info:type_name -> pb.Tug
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tug_proto_init() }
func file_tug_proto_init() {
	if File_tug_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tug_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tug_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TugScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tug_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2LS_TugClickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tug_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_TugClickRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tug_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LS2C_TugInfoNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tug_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tug_proto_goTypes,
		DependencyIndexes: file_tug_proto_depIdxs,
		EnumInfos:         file_tug_proto_enumTypes,
		MessageInfos:      file_tug_proto_msgTypes,
	}.Build()
	File_tug_proto = out.File
	file_tug_proto_rawDesc = nil
	file_tug_proto_goTypes = nil
	file_tug_proto_depIdxs = nil
}
