{
 "title": "Aniwar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Guide 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Login 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "登录延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_LoginDelayHist_sum/aniwar_LoginDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "登录成功",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_LoginSucceedCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "登录失败",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Gate 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "消息包数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "LoginGame延迟",
   "type": "graph",
   "description": "LoginGameReq 延迟",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_EnterDelayHist_sum/aniwar_EnterDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gate延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_GateDelayHist_sum/aniwar_GateDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "登录成功数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterSucceedCount" }
   ]
  },
  {
   "title": "Gate连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateConnCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "登录丢弃数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterDropCount" }
   ]
  },
  {
   "title": "上行消息包大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateUpMsgSize" }
   ]
  },
  {
   "title": "下行消息包大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateDownMsgSize" }
   ]
  },
  {
   "title": "Actor 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UserActor数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_UserActorCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UserInvoke延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_UserInvokeDelayHist_sum/aniwar_UserInvokeDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SrvInvoke延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_RoomInvokeDelayHist_sum/aniwar_RoomInvokeDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "日志监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "警告日志",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_WarnCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "错误日志",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_ErrorCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "redis读次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_RedisRCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "redis写次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_RedisWCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "redis写大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "redis读延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_RedisRDelayHist_sum/aniwar_RedisRDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "redis写延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_RedisWDelayHist_sum/aniwar_RedisWDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mongo读次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_MongoRCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mongo写次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_MongoWCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mongo写大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_MongoWSize" }
   ]
  },
  {
   "title": "mongo读延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_MongoRDelayHist_sum/aniwar_MongoRDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mongo写延迟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_MongoWDelayHist_sum/aniwar_MongoWDelayHist_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}