{
 "title": "Aniwar",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Guide 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Login 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "登录延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_LoginDelayHist_count" },
    { "expr": "aniwar_LoginDelayHist_average" },
    { "expr": "aniwar_LoginDelayHist_medium" },
    {
     "expr": "aniwar_LoginDelayHist_percent95"
    }
   ]
  },
  {
   "title": "登录成功",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_LoginSucceedCount" }
   ]
  },
  {
   "title": "登录失败",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_LoginFailedCount" }
   ]
  },
  {
   "title": "Gate 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "消息包数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateMsgCount" }
   ]
  },
  {
   "title": "LoginGame延迟",
   "type": "graph",
   "description": "LoginGameReq 延迟",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterDelayHist_average" },
    { "expr": "aniwar_EnterDelayHist_count" },
    { "expr": "aniwar_EnterDelayHist_medium" },
    {
     "expr": "aniwar_EnterDelayHist_percent95"
    }
   ]
  },
  {
   "title": "Gate延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateDelayHist_average" },
    { "expr": "aniwar_GateDelayHist_count" },
    { "expr": "aniwar_GateDelayHist_medium" },
    { "expr": "aniwar_GateDelayHist_percent95" }
   ]
  },
  {
   "title": "登录成功数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterSucceedCount" }
   ]
  },
  {
   "title": "登录失败数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterFailedCount" }
   ]
  },
  {
   "title": "登录丢弃数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_EnterDropCount" }
   ]
  },
  {
   "title": "上行消息包大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateUpMsgSize" }
   ]
  },
  {
   "title": "下行消息包大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aniwar_GateDownMsgSize" }
   ]
  },
  {
   "title": "Actor 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "UserActor数量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_UserActorCount" }
     ]
    },
    {
     "title": "UserInvoke延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_UserInvokeDelayHist_average"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_count"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_medium"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_percent95"
      }
     ]
    },
    {
     "title": "SrvInvoke延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_SrvInvokeDelayHist_average"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_count"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_medium"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_percent95"
      }
     ]
    }
   ]
  },
  {
   "title": "日志监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "警告日志",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_WarnCount" }
     ]
    },
    {
     "title": "错误日志",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_ErrorCount" }
     ]
    }
   ]
  },
  {
   "title": "Redis监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "redis读次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_RedisRCount" }
     ]
    },
    {
     "title": "redis写次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_RedisWCount" }
     ]
    },
    {
     "title": "redis写大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_RedisWSize" }
     ]
    },
    {
     "title": "redis读延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_RedisRDelayHist_average" },
      { "expr": "aniwar_RedisRDelayHist_count" },
      { "expr": "aniwar_RedisRDelayHist_medium" },
      {
       "expr": "aniwar_RedisRDelayHist_percent95"
      }
     ]
    },
    {
     "title": "redis写延迟",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_RedisWDelayHist_average" },
      { "expr": "aniwar_RedisWDelayHist_count" },
      { "expr": "aniwar_RedisWDelayHist_medium" },
      {
       "expr": "aniwar_RedisWDelayHist_percent95"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "mongo读次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_MongoRCount" }
     ]
    },
    {
     "title": "mongo写次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_MongoWCount" }
     ]
    },
    {
     "title": "mongo写大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_MongoWSize" }
     ]
    },
    {
     "title": "mongo读延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_MongoRDelayHist_average" }
     ]
    },
    {
     "title": "mongo写延迟",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_MongoWDelayHist_average" }
     ]
    }
   ]
  }
 ]
}