{
 "title": "Aniwar-Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rollingVersion", "label": "包版本", "query": { "query": "label_values(rollingVersion)" } },
   { "name": "guidePod", "query": { "query": "label_values(pod)" } },
   { "name": "loginPod", "query": { "query": "label_values(pod)" } },
   { "name": "gatePod", "query": { "query": "label_values(pod)" } },
   { "name": "actorPod", "query": { "query": "label_values(pod)" } },
   { "name": "idipPod", "query": { "query": "label_values(pod)" } },
   { "name": "lobbyPod", "query": { "query": "label_values(pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Guide 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Guide成功次数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GuideSucceedCount{rollingVersion=~\"$rollingVersion\", pod=~\"$guidePod\"}"
      }
     ]
    },
    {
     "title": "Guide失败次数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "aniwar_GuideFailedCount" }
     ]
    },
    {
     "title": "Guide延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GuideDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$guidePod\"}"
      },
      {
       "expr": "aniwar_GuideDelayHist_count{rollingVersion=~\"$rollingVersion\", pod=~\"$guidePod\"}"
      },
      {
       "expr": "aniwar_GuideDelayHist_medium{rollingVersion=~\"$rollingVersion\", pod=~\"$guidePod\"}"
      },
      {
       "expr": "aniwar_GuideDelayHist_percent95{rollingVersion=~\"$rollingVersion\", pod=~\"$guidePod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Login 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "登录延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_LoginDelayHist_count{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    },
    {
     "expr": "aniwar_LoginDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    },
    {
     "expr": "aniwar_LoginDelayHist_medium{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    },
    {
     "expr": "aniwar_LoginDelayHist_percent95{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    }
   ]
  },
  {
   "title": "登录成功",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_LoginSucceedCount{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    }
   ]
  },
  {
   "title": "登录失败",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aniwar_LoginFailedCount{rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
    }
   ]
  },
  {
   "title": "Gate 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "消息包数量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GateMsgCount{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "LoginGame延迟",
     "type": "graph",
     "description": "LoginGameReq 延迟",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_EnterDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_EnterDelayHist_count{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_EnterDelayHist_medium{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_EnterDelayHist_percent95{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "Gate延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GateDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "登录成功数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_EnterSucceedCount{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "登录失败数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_EnterFailedCount{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "登录丢弃数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_EnterDropCount{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "上行消息包大小",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GateUpMsgSize{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "下行消息包大小",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_GateDownMsgSize{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Actor 服",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "UserActor数量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_UserActorCount{rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    },
    {
     "title": "UserInvoke延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_UserInvokeDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_count{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_medium{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_UserInvokeDelayHist_percent95{rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "SrvInvoke延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_SrvInvokeDelayHist_average{rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod|$idipPod\"}"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_count{rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod|$idipPod\"}"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_medium{rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod|$idipPod\"}"
      },
      {
       "expr": "aniwar_SrvInvokeDelayHist_percent95{rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod|$idipPod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "日志监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "警告日志",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_WarnCount{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_WarnCount{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_WarnCount{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_WarnCount{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      }
     ]
    },
    {
     "title": "错误日志",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_ErrorCount{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_ErrorCount{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_ErrorCount{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_ErrorCount{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "redis读次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisRCount{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisRCount{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "redis写次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisWCount{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_RedisWCount{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "redis写大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisWSize{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisWSize{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_RedisWSize{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "actor读延迟",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisRDelayHist_average{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_count{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_medium{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_percent95{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    },
    {
     "title": "gate读延迟",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisRDelayHist_average{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_count{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_medium{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_percent95{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "idip读延迟",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisRDelayHist_average{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_count{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_medium{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      },
      {
       "expr": "aniwar_RedisRDelayHist_percent95{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      }
     ]
    },
    {
     "title": "login写延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisWDelayHist_average{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_count{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_medium{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_percent95{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      }
     ]
    },
    {
     "title": "gate写延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisWDelayHist_average{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_count{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_medium{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_percent95{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      }
     ]
    },
    {
     "title": "actor写延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_RedisWDelayHist_average{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_count{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_medium{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_RedisWDelayHist_percent95{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "mongo读次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_MongoRCount{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_MongoRCount{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_MongoRCount{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_MongoRCount{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      },
      {
       "expr": "aniwar_MongoRCount{appId=\"lobby\", rollingVersion=~\"$rollingVersion\", pod=~\"$lobbyPod\"}"
      }
     ]
    },
    {
     "title": "mongo写次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_MongoWCount{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_MongoWCount{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    },
    {
     "title": "mongo写大小",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_MongoWSize{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_MongoWSize{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    },
    {
     "title": "mongo读延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_MongoRDelayHist_average{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_MongoRDelayHist_average{appId=\"gate\", rollingVersion=~\"$rollingVersion\", pod=~\"$gatePod\"}"
      },
      {
       "expr": "aniwar_MongoRDelayHist_average{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      },
      {
       "expr": "aniwar_MongoRDelayHist_average{appId=\"idip\", rollingVersion=~\"$rollingVersion\", pod=~\"$idipPod\"}"
      },
      {
       "expr": "aniwar_MongoRDelayHist_average{appId=\"lobby\", rollingVersion=~\"$rollingVersion\", pod=~\"$lobbyPod\"}"
      }
     ]
    },
    {
     "title": "mongo写延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aniwar_MongoWDelayHist_average{appId=\"login\", rollingVersion=~\"$rollingVersion\", pod=~\"$loginPod\"}"
      },
      {
       "expr": "aniwar_MongoWDelayHist_average{appId=\"actor\", rollingVersion=~\"$rollingVersion\", pod=~\"$actorPod\"}"
      }
     ]
    }
   ]
  }
 ]
}